### ISSUE TITLE
No support for kernel version 5.13.0-7614-generic

### ISSUE THREAD

**Issue by Grant12311** [M-Bab/linux-kernel-amdgpu-binaries#100]
Yesterday I updated my POP OS system's Linux kernel to version 5.13.0-7614-generic via APT. Following a reboot, my PC crashed after login a few times in a row. Once it finally did boot, I noticed that my AMD GPU kernel was no longer being used. Am I correct that this is because this repository only supports up to 5.11.X? I would greatly appreciate some support resolving this issue, as I depend on these kernel binaries for certain GPU features.

**Comment by M-Bab** [comment]
I had several issues building the new 5.13 based kernel. Finally managed to complete it again (last thing missing was actually zstd :sweat_smile: ). Feel free to try it out. If this resolves your problem we can close this issue.

**Comment by M-Bab** [comment]
But in the FAQ are also instructions how to set your default kernel to boot. This works around when other kernels are ahead of this one.

**Comment by Grant12311** [comment]
Thanks for the quick response! I installed the new kernel as soon as you updated it and have booted my system successfully several times now. It looks like that did the trick. In case this happens again, am I supposed to set the default kernel to be the regular/latest kernel or override it with this one?

**Comment by M-Bab** [comment]
> In case this happens again, am I supposed to set the default kernel to be the regular/latest kernel or override it with this one?

Depends what works best for you. Usually you always want to boot the newest kernel. And (at least compared to Ubuntu schedule) my kernel should be >= concerning the version compared to the system kernel.
