### ISSUE TITLE
can not install the nvidia-driver

### ISSUE THREAD

**Issue by jzx-gooner** [M-Bab/linux-kernel-amdgpu-binaries#101]
Thanks for you nice work
When i upgrade the kernel 5.13.18 and i can not use nvidia-smi ,it shows
```
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```
i use "sudo dkms install -m nvidia -v 470.86" and it shows
```
Building module:
cleaning build area...
unset ARCH; [ ! -h /usr/bin/cc ] && export CC=/usr/bin/gcc; env NV_VERBOSE=1 'make' -j16 NV_EXCLUDE_BUILD_MODULES='' KERNEL_UNAME=5.13.18-21.09.16.amdgpu.ubuntu IGNORE_XEN_PRESENCE=1 IGNORE_CC_MISMATCH=1 SYSSRC=/lib/modules/5.13.18-21.09.16.amdgpu.ubuntu/build LD=/usr/bin/ld.bfd modules.....(bad exit status: 2)
ERROR (dkms apport): kernel package linux-headers-5.13.18-21.09.16.amdgpu.ubuntu is not supported
Error! Bad return status for module build on kernel: 5.13.18-21.09.16.amdgpu.ubuntu (x86_64)

```

Thank you very much

**Comment by M-Bab** [comment]
Yeah thats plausible. Most of the install scripts check for the specific kernel version and only support a small set of specific kernels
(most likely with special handling for some kernels). Of course the script has no idea what to do with this very special kernel.

Other question: Why would you ever want to install this kernel if you have an NVIDIA GPU? This kernel is a very dedicated kernel for AMD GPUs and I would not recommend to use it for NVIDIA GPUs.
