### ISSUE TITLE
PSA: 5.13.0-23 causing problems on APUs

### ISSUE THREAD

**Issue by MatthewForrester** [M-Bab/linux-kernel-amdgpu-binaries#103]
According to [a Reddit post ](https://www.reddit.com/r/Ubuntu/comments/rwnn7n/amd_ryzen_desktop_users_hold_off_with_513023/) pointing to [this bug report](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1956396) , the 5.13.0-23 update is causing problems for APU users' Vega graphics, in particular Picasso.

I thought this might be of interest to you, since the bug seems to directly affect your users. You are much better qualified than me to know whether you need to do anything about it.

P.S. While I am here, it seems that the commit messages on the update 6 days ago have a typo referring to 5.11.x instead of 5.13.x??

**Comment by MatthewForrester** [comment]
[A fix for this regression is in 5.13.0-24](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1956401/comments/11), currently in the -proposed archive.

**Comment by M-Bab** [comment]
https://github.com/M-Bab/linux-kernel-amdgpu-binaries/issues/23#issuecomment-1336514067
