### ISSUE TITLE
zst compression

### ISSUE THREAD

**Issue by andyburn70** [M-Bab/linux-kernel-amdgpu-binaries#104]
The 5.11 release works fine on Debian Bullseye amd64.
I have been unable to install the new 5.13.19 binaries apparently due to the use of zst compression, which I believe Debian does not support.
Is there a workaround?

root@darth:/home/darth/devel/linux-kernel-amdgpu-binaries# dpkg -i linux-headers-5.13.19-21.12.27.amdgpu_5.13.19-21.12.27.amdgpu-1_amd64.deb 
dpkg-deb: error: archive 'linux-headers-5.13.19-21.12.27.amdgpu_5.13.19-21.12.27.amdgpu-1_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive linux-headers-5.13.19-21.12.27.amdgpu_5.13.19-21.12.27.amdgpu-1_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 linux-headers-5.13.19-21.12.27.amdgpu_5.13.19-21.12.27.amdgpu-1_amd64.deb

Thanks,
Andy

**Comment by Tanetal77** [comment]
I can second this, the previous (marvellous!) release 5.11 is still working as expected after upgrading Linux Mint Debian Edition 4 to 5 (buster to bullseye), but the new release cannot be installed due to lacking zstd-support in debian's dpkg.
Maybe you could (if you have the time for it) prepare a debian build with default xz?

Thank you for your excellent work and sharing!
Ben

**Comment by themoonisacheese** [comment]
ran into this issue today.
workaround from [here](https://www.dolibarr.org/forum/t/unable-to-install-dolibarr-15-0-2-4-all-deb-on-debian-11-bullseye/22355):
```bash
sudo apt install zstd binutils
ar x [path to bad deb]
unzstd control.tar.zst
unzstd data.tar.zst
xz control.tar
xz data.tar
ar cr [file].deb debian-binary control.tar.xz data.tar.xz
sudo dpkg -i [file].deb
```

you have to do this twice, once for the headers and once for the image.
so far the install has worked, but i am yet to reboot.

**Comment by themoonisacheese** [comment]
ran into this issue today.
workaround from [here](https://www.dolibarr.org/forum/t/unable-to-install-dolibarr-15-0-2-4-all-deb-on-debian-11-bullseye/22355):
```bash
#!/bin/sh
sudo apt install zstd binutils
ar x [path to bad deb]
unzstd control.tar.zst
unzstd data.tar.zst
xz control.tar
xz data.tar
ar cr [file].deb debian-binary control.tar.xz data.tar.xz
sudo dpkg -i [file].deb
```

you have to do this twice, once for the headers and once for the image, then also dpkg the last .deb (you don't need to repack it)
This worked for me (i now have appropriate res)  on a fresh debian 11 install running on a 5600G (no dGPU)

**Comment by M-Bab** [comment]
https://github.com/M-Bab/linux-kernel-amdgpu-binaries/issues/23#issuecomment-1336514067
