### ISSUE TITLE
Set `CONFIG_KALLSYMS_ALL=y` so vendor-reset can be used.

### ISSUE THREAD

**Issue by stuaxo** [M-Bab/linux-kernel-amdgpu-binaries#105]
Would it be possible to enable `CONFIG_KALLSYMS_ALL=y` this would make enable the use of https://github.com/gnif/vendor-reset I'm curious whether that would help an issue I have, where when I come out of sleep I can't get back to wayland / X.

The docs of vendor-reset say:

> ## Requirements
> 
> Ensure your kernel has the following options enabled:
> 
> ```
> CONFIG_FTRACE=y
> CONFIG_KPROBES=y
> CONFIG_PCI_QUIRKS=y
> CONFIG_KALLSYMS=y
> CONFIG_KALLSYMS_ALL=y
> CONFIG_FUNCTION_TRACER=y
> ```

Checking the settings, I can see all but KALLSYSMS_ALL are set:

```bash
cat /boot/config-`uname -r` | egrep 'CONFIG_FTRACE=|CONFIG_KPROBES=|CONFIG_PCI_QUIRKS=|CONFIG_KALLSYMS=|CONFIG_KALLSYMS_ALL=|CONFIG_FUNCTION_TRACER=' | sort
CONFIG_FTRACE=y
CONFIG_FUNCTION_TRACER=y
CONFIG_KALLSYMS=y
CONFIG_KPROBES=y
CONFIG_PCI_QUIRKS=y
```

**Comment by M-Bab** [comment]
https://github.com/M-Bab/linux-kernel-amdgpu-binaries/issues/23#issuecomment-1336514067
