### ISSUE TITLE
R9 280x sound doesn't work via Display port.

### ISSUE THREAD

**Issue by IDispatcher** [M-Bab/linux-kernel-amdgpu-binaries#13]
Sound on MSI 280x doesn't work via DispalyPort. At the same time it works correctly via HDMI.

>>
Ubuntu 17.04
>>
uname -a
Linux BigOne 4.11.11+ #1 SMP Sun Jul 16 11:05:40 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by M-Bab** [comment]
Are you 100% sure this isn't a configuration issue? E.g. if I switch from HDMI to Display Port I have to change the digital stereo output of my GPU in the sound control. Totally there are 6 outputs listed (HDMI - HDMI6) and only one is not tagged with "unplugged". I use pavucontrol as audio mixer UI.

**Comment by M-Bab** [comment]
Could you resolve the issue via configuration?

**Comment by IDispatcher** [comment]
Hello !

Yes, I check configuration in PulseAudio Volume control and select proper port.
Moreover pavucontrol show me that audio is actually streamed in linux. (See attached screenshot)
But everything works well if I switch to HDMI port on the same videocard.
So I can suppose that issue isn't in kernel, but in my display.
![screenshot from 2017-07-22 19-31-27](https://user-images.githubusercontent.com/1553900/28492993-b932de80-6f16-11e7-82aa-878d2e9441b4.png)

**Comment by M-Bab** [comment]
Okay then I close the issue for now.
When you have the chance to test the display port of another display or with another OS and then surprisingly it shows that it is NOT the display's fault just re-open the case.
