### ISSUE TITLE
Computer freezes on wifi network change

### ISSUE THREAD

**Issue by juanfe190** [M-Bab/linux-kernel-amdgpu-binaries#16]
If I try to change my wifi network computer freezes. This after updating to latest commit
Ubuntu 16.04.3

**Comment by M-Bab** [comment]
Hi! Thanks for the bug report. First step: Try the newest kernel I uploaded yesterday and give me feedback if it solved the problem or not.

If not I will need some more information and tests from your side:

- The problem does not occurs if you use an older amdgpu-kernel? Or the official Ubuntu kernel?
- Which is the oldest kernel where the problem started?
- Have you tried other mesa drivers? Does returning to the original drivers with ppa-purge help?
- The outputs of "dmesg | grep amdgpu", "lsmod | grep amdgpu", "dpkg -l | grep firmware" and "dpkg -l | grep mesa"

**Comment by juanfe190** [comment]
It stopped happening with the network, but I still get random freezes now and then, not really that often. Not sure if I can do anything to help you figure it out or if its just my computer.
