### ISSUE TITLE
New dmesg errors

### ISSUE THREAD

**Issue by DarkFoss** [M-Bab/linux-kernel-amdgpu-binaries#21]
Hi mbab,
I've been having various issues with the amdgpu kernels starting from 4.12.10+ do to the deduplication efforts. My Fury X fails to reinitialize the monitor coming out of S3, will hand on various benchmarks ect often needing to alt+sysrescue then ctr+alt+del 3 times before the card will reinitialize the monitor. Full dmesg on pastebin here 4.13.0+:  https://pastebin.com/ruVECqus

Let me know what else you need fyi same issue with the non ubuntu flavors.

**Comment by M-Bab** [comment]
I got an additional trace section in the dmesg since 4.13 as well but this isn't harmful.
The other stuff sound ugly.

Did you install the most recent firmware binaries?
Can you cross-check with an official Ubuntu 4.13 vanilla kernel if the problem remains or not? http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.13/

**Comment by DarkFoss** [comment]
Yep I used the latest binaries. I installed yesterdays 4.13 drm_tip no issues there but not surprising since they generally lag 7-14 days behind with the pulls. I'll continue to try the new kernels as you supply them see if the issues get cleaned up with the continual code churn. Guess it may be time to read up on git/bisect just in case.

**Comment by M-Bab** [comment]
Yeah patience till the code updates come might be a good idea.
You can try to git bisect on my source tree if you like - sorry I can't help because I cannot reproduce the issue.

**Comment by M-Bab** [comment]
I got too much feedback concerning instabilities so I reverted to kernel 4.12 and merged the commits from today. Also amd-staging-4.12 gets more updates by the AMD devs. As long as kernel 4.12 is not EOL yet there is no reason to jump on 4.13.

**Comment by DarkFoss** [comment]
I did a sudo do-release-upgrade -d to 17.10 outside of an odd cryptswap error it went smooth enough. It's not caused by your kernel just to be clear. Will do a clean install once artful is officially released.

Your 4.12.12 kernel is working fine with artful. I'm sure artful using the 4.12 kernel by default with matching tools helps. I'll install the 4.12.10+ just out of curiosity. 

Thanks for switching back from the 4.13 btw, having known good 4.12 kernels will make any  git/bisecting a lot easier should the need arise. I consider this issue fixed.
