### ISSUE TITLE
RX 570

### ISSUE THREAD

**Issue by mw-ferretti** [M-Bab/linux-kernel-amdgpu-binaries#22]
Hi mbab,
Only version 4.12 is stable for me. Version 4.13+ is locking the X, and I have to restart the computer manually.
My Settings:
Ubuntu Gnome 17.04 + RX570 asus strix

**Comment by M-Bab** [comment]
I got too much feedback concerning instabilities so I reverted to kernel 4.12 and merged the commits from today. Also amd-staging-4.12 gets more updates by the AMD devs. As long as kernel 4.12 is not EOL yet there is no reason to jump on 4.13.

**Comment by mw-ferretti** [comment]
OK. Thank you for your work.
