### ISSUE TITLE
Debian Sid testing

### ISSUE THREAD

**Issue by reanimastudios** [M-Bab/linux-kernel-amdgpu-binaries#25]
Fails with a blank screen and virtual terminals not working on regular boot. However, booting into single user and dropping into root, then escaping back out allowing the boot process to proceed to multi-user allowed the process to finish.

mdriftmeyer@horus:/usr/lib/x86_64-linux-gnu$ uname -a
Linux horus 4.12.13+ #1 SMP Fri Sep 15 15:17:23 CEST 2017 x86_64 GNU/Linux
mdriftmeyer@horus:/usr/lib/x86_64-linux-gnu$

**Comment by M-Bab** [comment]
Well ... thats not how it is supposed to work. Do you have any log or terminal message that could explain what is causing the problem?

Furthermore I would glad to get some additional information:
1. Which GPU are you using?
2. Which kernel version are you using? Vanilla or Ubuntu? Have you tried the other one?
3. Which is the oldest kernel where the problem started (if there was an older trouble-free kernel)?
4. Have you tried other mesa drivers?
5. The outputs of "dmesg | grep amdgpu", "lsmod | grep amdgpu", "dpkg -l | grep firmware" and "dpkg -l | grep mesa"

**Comment by reanimastudios** [comment]
Oddly, the kernel has been stable. I’m more akin to thinking it’s gdm3 hiccups as the new gdm3 3.26 and the rest of GNOME 3.26 are rolling into Debian Sid. I’ll test a straight reboot once Mesa 17.2.1 is pushed to Sid and give you more feedback.

mdriftmeyer@horus:~/deb-tmp$ dmesg | grep amdgpu
mdriftmeyer@horus:~/deb-tmp$ lsmod | grep amdgpu
amdgpu               2830336  31
ttm                    90112  1 amdgpu
drm_kms_helper        131072  1 amdgpu
drm                   307200  16 amdgpu,ttm,drm_kms_helper
i2c_algo_bit           16384  1 amdgpu
mdriftmeyer@horus:~/deb-tmp$ dpkg -l | grep firmware
ii  alsa-firmware-loaders                         1.1.3-1                              amd64        ALSA software loaders for specific hardware
ii  amd64-microcode                               3.20160316.3                         amd64        Processor microcode firmware for AMD CPUs
ii  bluez-firmware                                1.2-3                                all          Firmware for Bluetooth devices
ii  firmware-amd-graphics                         20170823-1                           all          Binary firmware for AMD/ATI graphics chips
ii  firmware-intel-sound                          20170823-1                           all          Binary firmware for Intel sound DSPs
ii  firmware-linux-free                           3.4                                  all          Binary firmware for various drivers in the Linux kernel
ii  firmware-linux-nonfree                        20170823-1                           all          Binary firmware for various drivers in the Linux kernel (meta-package)
ii  firmware-misc-nonfree                         20170823-1                           all          Binary firmware for various drivers in the Linux kernel
ii  firmware-realtek                              20170823-1                           all          Binary firmware for Realtek wired/wifi/BT adapters
ii  ipxe-qemu                                     1.0.0+git-20161027.b991c67-1         all          PXE boot firmware - ROM images for qemu
mdriftmeyer@horus:~/deb-tmp$ dpkg -l | grep mesa
ii  glx-alternative-mesa                          0.8.0                                amd64        allows the selection of MESA as GLX provider
ii  libegl-mesa0:amd64                            17.2.0-2                             amd64        free implementation of the EGL API -- Mesa vendor library
ii  libegl1-mesa:amd64                            17.2.0-2                             amd64        transitional dummy package
ii  libegl1-mesa-dev:amd64                        17.2.0-2                             amd64        free implementation of the EGL API -- development files
ii  libegl1-mesa-drivers:amd64                    17.0.0~rc2-1                         amd64        transitional dummy package
ii  libgl1-mesa-dev:amd64                         17.2.0-2                             amd64        free implementation of the OpenGL API -- GLX development files
ii  libgl1-mesa-dri:amd64                         17.2.0-2                             amd64        free implementation of the OpenGL API -- DRI modules
ii  libgl1-mesa-glx:amd64                         17.2.0-2                             amd64        transitional dummy package
ii  libglapi-mesa:amd64                           17.2.0-2                             amd64        free implementation of the GL API -- shared library
ii  libgles2-mesa:amd64                           17.2.0-2                             amd64        transitional dummy package
ii  libgles2-mesa-dev:amd64                       17.2.0-2                             amd64        free implementation of the OpenGL|ES 2.x API -- development files
ii  libglu1-mesa:amd64                            9.0.0-2.1                            amd64        Mesa OpenGL utility library (GLU)
ii  libglu1-mesa-dev:amd64                        9.0.0-2.1                            amd64        Mesa OpenGL utility library -- development files
ii  libglx-mesa0:amd64                            17.2.0-2                             amd64        free implementation of the OpenGL API -- GLX vendor library
ii  libosmesa6:amd64                              17.2.0-2                             amd64        Mesa Off-screen rendering extension
ii  libosmesa6-dev:amd64                          17.2.0-2                             amd64        Mesa Off-screen rendering extension -- development files
ii  libwayland-egl1-mesa:amd64                    17.2.0-2                             amd64        implementation of the Wayland EGL platform -- runtime
ii  mesa-common-dev:amd64                         17.2.0-2                             amd64        Developer documentation for Mesa
ii  mesa-opencl-icd:amd64                         17.2.0-2                             amd64        free implementation of the OpenCL API -- ICD runtime
ii  mesa-utils                                    8.3.0-5                              amd64        Miscellaneous Mesa GL utilities
ii  mesa-utils-extra                              8.3.0-5                              amd64        Miscellaneous Mesa utilies (opengles, egl)
ii  mesa-va-drivers:amd64                         17.2.0-2                             amd64        Mesa VA-API video acceleration drivers
ii  mesa-vdpau-drivers:amd64                      17.2.0-2                             amd64        Mesa VDPAU video acceleration drivers
ii  mesa-vulkan-drivers:amd64                     17.2.0-2                             amd64        Mesa Vulkan graphics drivers

—————————

It’s been quite stable and I hope AMD gets this pushed upstream fast, but even more the ROCm code. Getting really tired having an OpenCL box being worthless for Blender and any scientific number crunching because Mesa is stuck on 1.1 OpenCL.

- Marc

Marc Jeffrey Driftmeyer
Founder & CEO of Reanimality Studios LLC
Cell: (509) 435-5212
url: https://www.reanimastudios.com <https://www.reanimastudios.com/>
url: https://www.holoworlds.net <https://www.holoworlds.net/>
email: mjd@reanimality.com <mailto:mjd@reanimality.com>
email: mjd@holoworlds.net <mailto:mjd@holoworlds.net>

**Comment by M-Bab** [comment]
I am thinking about making a pseudo amdgpu kernel OpenCl package without installing the full amdgpu-pro driver. Would you be interested to test it?

It works like this: https://steemit.com/linux/@woojoo/how-to-installing-opencl-for-lightweight-eth-mining-on-mesa-driver-environment-in-ubuntu

It is still no ROCm though.

**Comment by reanimastudios** [comment]
For me, what I’m missing is an active OpenCL stack that Blender recognizes. That’s my primary interest. If that is included then fire away. AMD has made OpenCL better than CUDA on Blender, yet it’s DOA on Linux outside of Ubuntu, which I will never rebase my entire workflow around. It’s been nearly 12 months and still no viable OpenCL on Debian because AMD still hasn’t gotten off it’s ass and fixed DKMS support and made a proper agnostic installed OpenCL stack. It seems rather clear they have legal/contractual ties that have been delaying that decoupling from the rest of their code base.

- Marc

Marc Jeffrey Driftmeyer
Founder & CEO of Reanimality Studios LLC
Cell: (509) 435-5212
url: https://www.reanimastudios.com <https://www.reanimastudios.com/>
url: https://www.holoworlds.net <https://www.holoworlds.net/>
email: mjd@reanimality.com <mailto:mjd@reanimality.com>
email: mjd@holoworlds.net <mailto:mjd@holoworlds.net>
