### ISSUE TITLE
Error installing the kernel --> Black Screen Cinnamon crash

### ISSUE THREAD

**Issue by Tormund1985** [M-Bab/linux-kernel-amdgpu-binaries#28]
Output: **inxi -Fxz:** 
`System:    Host: tormund-PC Kernel: 4.10.0-35-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.4.6 (Gtk 3.18.9-1ubuntu3.3)
           Distro: Linux Mint 18.2 Sonya
Machine:   Mobo: ASUSTeK model: M5A78L-M/USB3 v: Rev X.0x
           Bios: American Megatrends v: 2101 date: 12/02/2014
CPU:       Quad core AMD Athlon II X4 640 (-MCP-) cache: 2048 KB
           flags: (lm nx sse sse2 sse3 sse4a svm) bmips: 27961
           clock speeds: max: 3495 MHz 1: 3495 MHz 2: 3495 MHz 3: 3495 MHz
           4: 3495 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Device 67df bus-ID: 01:00.0
           Display Server: X.Org 1.18.4 drivers: ati,amdgpu (unloaded: fbdev,vesa,radeon)
           Resolution: 1920x1080@60.00hz
           GLX Renderer: Gallium 0.4 on AMD POLARIS10 (DRM 3.9.0 / 4.10.0-35-generic, LLVM 4.0.0)
           GLX Version: 3.0 Mesa 17.0.7 Direct Rendering: Yes
Audio:     Card-1 Advanced Micro Devices [AMD/ATI] Device aaf0
           driver: snd_hda_intel bus-ID: 01:00.1
           Card-2 Advanced Micro Devices [AMD/ATI] SBx00 Azalia (Intel HDA)
           driver: snd_hda_intel bus-ID: 00:14.2
           Sound: Advanced Linux Sound Architecture v: k4.10.0-35-generic
Network:   Card: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169 v: 2.3LK-NAPI port: e800 bus-ID: 03:00.0
           IF: enp3s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
Drives:    HDD Total Size: 9241.8GB (90.6% used)
           ID-1: USB /dev/sda model: Expansion_Desk size: 5001.0GB
           ID-2: /dev/sdb model: WDC_WD20EARS size: 2000.4GB
           ID-3: /dev/sdc model: CT240BX200SSD1 size: 240.1GB
           ID-4: /dev/sdd model: WDC_WD20EARS size: 2000.4GB
Partition: ID-1: / size: 159G used: 99G (66%) fs: ext4 dev: /dev/sdc4
           ID-2: swap-1 size: 4.09GB used: 0.00GB (0%) fs: swap dev: /dev/sdc5
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 36.0C mobo: 36.0C gpu: 33.0
           Fan Speeds (in rpm): cpu: 1464 sys-1: 1115
Info:      Processes: 249 Uptime: 10 min Memory: 2599.4/7980.1MB
           Init: systemd runlevel: 5 Gcc sys: 5.4.0
           Client: Shell (bash 4.3.481) inxi: 2.2.35 
`

Output: **dmesg | grep amdgpu**:
`[    2.224824] [drm] amdgpu kernel modesetting enabled.
[    2.233948] fb: switching to amdgpudrmfb from VESA VGA
[    2.234567] amdgpu 0000:01:00.0: Invalid PCI ROM header signature: expecting 0xaa55, got 0xffff
[    2.235473] amdgpu 0000:01:00.0: VRAM: 8192M 0x0000000000000000 - 0x00000001FFFFFFFF (8192M used)
[    2.235475] amdgpu 0000:01:00.0: GTT: 8192M 0x0000000200000000 - 0x00000003FFFFFFFF
[    2.235897] [drm] amdgpu: 8192M of VRAM memory ready
[    2.235899] [drm] amdgpu: 8192M of GTT memory ready.
[    2.237181] amdgpu 0000:01:00.0: amdgpu: using MSI.
[    2.237199] [drm] amdgpu: irq initialized.
[    2.237371] amdgpu: powerplay initialized
[    2.238722] amdgpu 0000:01:00.0: fence driver on ring 0 use gpu addr 0x0000000200000008, cpu addr 0xffff895ce55e9008
[    2.238878] amdgpu 0000:01:00.0: fence driver on ring 1 use gpu addr 0x0000000200000018, cpu addr 0xffff895ce55e9018
[    2.239038] amdgpu 0000:01:00.0: fence driver on ring 2 use gpu addr 0x0000000200000028, cpu addr 0xffff895ce55e9028
[    2.239187] amdgpu 0000:01:00.0: fence driver on ring 3 use gpu addr 0x0000000200000038, cpu addr 0xffff895ce55e9038
[    2.239334] amdgpu 0000:01:00.0: fence driver on ring 4 use gpu addr 0x0000000200000048, cpu addr 0xffff895ce55e9048
[    2.239485] amdgpu 0000:01:00.0: fence driver on ring 5 use gpu addr 0x0000000200000058, cpu addr 0xffff895ce55e9058
[    2.239654] amdgpu 0000:01:00.0: fence driver on ring 6 use gpu addr 0x0000000200000068, cpu addr 0xffff895ce55e9068
[    2.239865] amdgpu 0000:01:00.0: fence driver on ring 7 use gpu addr 0x0000000200000078, cpu addr 0xffff895ce55e9078
[    2.240016] amdgpu 0000:01:00.0: fence driver on ring 8 use gpu addr 0x0000000200000088, cpu addr 0xffff895ce55e9088
[    2.240232] amdgpu 0000:01:00.0: fence driver on ring 9 use gpu addr 0x0000000200000098, cpu addr 0xffff895ce55e9098
[    2.240378] amdgpu 0000:01:00.0: fence driver on ring 10 use gpu addr 0x00000002000000a8, cpu addr 0xffff895ce55e90a8
[    2.241083] amdgpu 0000:01:00.0: fence driver on ring 11 use gpu addr 0x000000000109c420, cpu addr 0xffffa77a4325a420
[    2.241432] amdgpu 0000:01:00.0: fence driver on ring 12 use gpu addr 0x00000002000000c8, cpu addr 0xffff895ce55e90c8
[    2.241482] amdgpu 0000:01:00.0: fence driver on ring 13 use gpu addr 0x00000002000000d8, cpu addr 0xffff895ce55e90d8
[    2.582590] fbcon: amdgpudrmfb (fb0) is primary device
[    2.582702] amdgpu 0000:01:00.0: fb0: amdgpudrmfb frame buffer device
[    2.805665] [drm] Initialized amdgpu 3.9.0 20150101 for 0000:01:00.0 on minor 0
`

Output: **lsmod | grep amdgpu:**
`amdgpu               1560576  22
i2c_algo_bit           16384  1 amdgpu
ttm                    98304  1 amdgpu
drm_kms_helper        151552  1 amdgpu
drm                   352256  10 amdgpu,ttm,drm_kms_helper
`

Output: **dpkg -l | grep firmware:**
`ii  amd64-microcode                                                  2.20160316.1                                 amd64        Processor microcode firmware for AMD CPUs
ii  firmware-radeon-ucode                                            1.50                                         all          Firmware binaries for modern AMD GPUs
ii  fwupdate                                                         0.5-2ubuntu5                                 amd64        Tools to manage UEFI firmware updates
ii  libfwup0:amd64                                                   0.5-2ubuntu5                                 amd64        Library to manage UEFI firmware updates
ii  linux-firmware                                                   1.157.12                                     all          Firmware for Linux kernel drivers`

Output: **dpkg -l | grep mesa:**
`ii  libegl1-mesa:amd64                                               17.0.7-0ubuntu0.16.04.1                      amd64        free implementation of the EGL API -- runtime
ii  libegl1-mesa-drivers:amd64                                       12.0.6-0ubuntu0.16.04.1                      amd64        transitional dummy package
ii  libgl1-mesa-dri:amd64                                            17.0.7-0ubuntu0.16.04.1                      amd64        free implementation of the OpenGL API -- DRI modules
ii  libgl1-mesa-glx:amd64                                            17.0.7-0ubuntu0.16.04.1                      amd64        free implementation of the OpenGL API -- GLX runtime
ii  libglapi-mesa:amd64                                              17.0.7-0ubuntu0.16.04.1                      amd64        free implementation of the GL API -- shared library
ii  libgles2-mesa:amd64                                              17.0.7-0ubuntu0.16.04.1                      amd64        free implementation of the OpenGL|ES 2.x API -- runtime
ii  libglu1-mesa:amd64                                               9.0.0-2.1                                    amd64        Mesa OpenGL utility library (GLU)
ii  libwayland-egl1-mesa:amd64                                       17.0.7-0ubuntu0.16.04.1                      amd64        implementation of the Wayland EGL platform -- runtime
ii  mesa-utils                                                       8.3.0-1                                      amd64        Miscellaneous Mesa GL utilities
`

**Comment by M-Bab** [comment]
Okay now step by step:
Which kernel did you install? Are there any error messages on install? What happens exactly when you try to boot? Does the crash only affect the GUI or doesn't it even reach the console?
Have you removed the amdgpu-pro driver before trying to boot to this kernel?

I mean your outputs look fine but this is not from an amdgpu kernel.

**Comment by Tormund1985** [comment]
What I do is download your kernel 4.12 and 4.9 and installed. Only this. The install reports errors and when I reboot: Black Screen and I can't enter in mode console. I can enter by advanced option but en render mode and cinnamon crash. 

Then, I have to remove the kernel 4.12 and 4.9. I dont have installed amdgpu pro.

I installed your kernel in a clean installation of Linux Mint 18.2 with X.org and Mesa. Without Amdgpu pro.

**Comment by M-Bab** [comment]
Okay WHAT error messages do you get when you install the kernels?
And after a boot failure when you boot a working kernel can you look for any error messages of the previous failed boot in /var/log/ ?

**Comment by Tormund1985** [comment]
The error's during the install are the same that shows Enigma0 in their issue.
When I have time again I will try to install the kernel and look for any error in /var/log.

**Comment by M-Bab** [comment]
So when you have the same error like Enigma, you are running VMware as well?

**Comment by Tormund1985** [comment]
No I dont have installed VMware, I am using Virtualbox. The error that shows repeately is that:
Error! Bad return status for module build on kernel: 4.12.9+ (x86_64)
Consult /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/make.log for more information.

Also in kernel 4.9.5.

**Comment by Tormund1985** [comment]
The same error installing the kernel 4.13:

`Seleccionando el paquete linux-headers-4.13.0-041300 previamente no seleccionado.
(Leyendo la base de datos ... 361559 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar linux-headers-4.13.0-041300_4.13.0-041300.201709031731_all.deb ...
Desempaquetando linux-headers-4.13.0-041300 (4.13.0-041300.201709031731) ...
Seleccionando el paquete linux-headers-4.13.0-041300-generic previamente no seleccionado.
Preparando para desempaquetar linux-headers-4.13.0-041300-generic_4.13.0-041300.201709031731_amd64.deb ...
Desempaquetando linux-headers-4.13.0-041300-generic (4.13.0-041300.201709031731) ...
Seleccionando el paquete linux-headers-4.13.0-041300-lowlatency previamente no seleccionado.
Preparando para desempaquetar linux-headers-4.13.0-041300-lowlatency_4.13.0-041300.201709031731_amd64.deb ...
Desempaquetando linux-headers-4.13.0-041300-lowlatency (4.13.0-041300.201709031731) ...
Seleccionando el paquete linux-image-4.13.0-041300-generic previamente no seleccionado.
Preparando para desempaquetar linux-image-4.13.0-041300-generic_4.13.0-041300.201709031731_amd64.deb ...
Done.
Desempaquetando linux-image-4.13.0-041300-generic (4.13.0-041300.201709031731) ...
Seleccionando el paquete linux-image-4.13.0-041300-lowlatency previamente no seleccionado.
Preparando para desempaquetar linux-image-4.13.0-041300-lowlatency_4.13.0-041300.201709031731_amd64.deb ...
Done.
Desempaquetando linux-image-4.13.0-041300-lowlatency (4.13.0-041300.201709031731) ...
Configurando linux-headers-4.13.0-041300 (4.13.0-041300.201709031731) ...
Configurando linux-headers-4.13.0-041300-generic (4.13.0-041300.201709031731) ...
Examining /etc/kernel/header_postinst.d.
run-parts: executing /etc/kernel/header_postinst.d/dkms 4.13.0-041300-generic /boot/vmlinuz-4.13.0-041300-generic
Error! Bad return status for module build on kernel: 4.13.0-041300-generic (x86_64)
Consult /var/lib/dkms/ndiswrapper/1.60/build/make.log for more information.
Error! Bad return status for module build on kernel: 4.13.0-041300-generic (x86_64)
Consult /var/lib/dkms/virtualbox-guest/5.0.40/build/make.log for more information.
Configurando linux-headers-4.13.0-041300-lowlatency (4.13.0-041300.201709031731) ...
Examining /etc/kernel/header_postinst.d.
run-parts: executing /etc/kernel/header_postinst.d/dkms 4.13.0-041300-lowlatency /boot/vmlinuz-4.13.0-041300-lowlatency
Error! Bad return status for module build on kernel: 4.13.0-041300-lowlatency (x86_64)
Consult /var/lib/dkms/ndiswrapper/1.60/build/make.log for more information.
Error! Bad return status for module build on kernel: 4.13.0-041300-lowlatency (x86_64)
Consult /var/lib/dkms/virtualbox-guest/5.0.40/build/make.log for more information.
Configurando linux-image-4.13.0-041300-generic (4.13.0-041300.201709031731) ...
Running depmod.
update-initramfs: deferring update (hook will be called later)
Examining /etc/kernel/postinst.d.
run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 4.13.0-041300-generic /boot/vmlinuz-4.13.0-041300-generic
run-parts: executing /etc/kernel/postinst.d/dkms 4.13.0-041300-generic /boot/vmlinuz-4.13.0-041300-generic
Error! Bad return status for module build on kernel: 4.13.0-041300-generic (x86_64)
Consult /var/lib/dkms/ndiswrapper/1.60/build/make.log for more information.
Error! Bad return status for module build on kernel: 4.13.0-041300-generic (x86_64)
Consult /var/lib/dkms/virtualbox-guest/5.0.40/build/make.log for more information.
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 4.13.0-041300-generic /boot/vmlinuz-4.13.0-041300-generic
update-initramfs: Generating /boot/initrd.img-4.13.0-041300-generic
W: Possible missing firmware /lib/firmware/amdgpu/raven_gpu_info.bin for module amdgpu
Warning: No support for locale: es_ES.utf8
^CFailed to process /etc/kernel/postinst.d at /var/lib/dpkg/info/linux-image-4.13.0-041300-generic.postinst line 1052.
dpkg: error al procesar el paquete linux-image-4.13.0-041300-generic (--install):
 el subproceso instalado el script post-installation devolvió el código de salida de error 2
Configurando linux-image-4.13.0-041300-lowlatency (4.13.0-041300.201709031731) ...
Running depmod.
update-initramfs: deferring update (hook will be called later)
Examining /etc/kernel/postinst.d.
run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 4.13.0-041300-lowlatency /boot/vmlinuz-4.13.0-041300-lowlatency
run-parts: executing /etc/kernel/postinst.d/dkms 4.13.0-041300-lowlatency /boot/vmlinuz-4.13.0-041300-lowlatency
Error! Bad return status for module build on kernel: 4.13.0-041300-lowlatency (x86_64)
Consult /var/lib/dkms/ndiswrapper/1.60/build/make.log for more information.
Error! Bad return status for module build on kernel: 4.13.0-041300-lowlatency (x86_64)
Consult /var/lib/dkms/virtualbox-guest/5.0.40/build/make.log for more information.
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 4.13.0-041300-lowlatency /boot/vmlinuz-4.13.0-041300-lowlatency
update-initramfs: Generating /boot/initrd.img-4.13.0-041300-lowlatency
W: Possible missing firmware /lib/firmware/amdgpu/raven_gpu_info.bin for module amdgpu
Warning: No support for locale: es_ES.utf8
run-parts: executing /etc/kernel/postinst.d/pm-utils 4.13.0-041300-lowlatency /boot/vmlinuz-4.13.0-041300-lowlatency
run-parts: executing /etc/kernel/postinst.d/zz-update-grub 4.13.0-041300-lowlatency /boot/vmlinuz-4.13.0-041300-lowlatency
Generando archivo de configuración grub...
Encontrada imagen de linux: /boot/vmlinuz-4.13.0-041300-lowlatency
Encontrada imagen de memoria inicial: /boot/initrd.img-4.13.0-041300-lowlatency
Encontrada imagen de linux: /boot/vmlinuz-4.13.0-041300-generic
Encontrada imagen de memoria inicial: /boot/initrd.img-4.13.0-041300-generic
Encontrada imagen de linux: /boot/vmlinuz-4.10.0-35-generic
Encontrada imagen de memoria inicial: /boot/initrd.img-4.10.0-35-generic
Encontrada imagen de linux: /boot/vmlinuz-4.8.0-58-generic
Encontrada imagen de memoria inicial: /boot/initrd.img-4.8.0-58-generic
Encontrada imagen de linux: /boot/vmlinuz-4.8.0-53-generic
Encontrada imagen de memoria inicial: /boot/initrd.img-4.8.0-53-generic
Found memtest86+ image: /boot/memtest86+.elf
Found memtest86+ image: /boot/memtest86+.bin
ERROR: unsupported sector size 4096 on /dev/sda.
ERROR: unsupported sector size 4096 on /dev/sda.
ERROR: unsupported sector size 4096 on /dev/sda.
ERROR: unsupported sector size 4096 on /dev/sda.
ERROR: unsupported sector size 4096 on /dev/sda.
ERROR: unsupported sector size 4096 on /dev/sda.
ERROR: unsupported sector size 4096 on /dev/sda.
ERROR: unsupported sector size 4096 on /dev/sda.
ERROR: unsupported sector size 4096 on /dev/sda.
Encontrado Windows 10 (loader) en /dev/sdc1
Encontrado Windows 10 (loader) en /dev/sdc2
hecho
Se encontraron errores al procesar:
 linux-image-4.13.0-041300-generic
`

**Comment by M-Bab** [comment]
Okay, you should have a look at
/var/lib/dkms/ndiswrapper/1.60/build/make.log
and
/var/lib/dkms/virtualbox-guest/5.0.40/build/make.log
This error can happen when trying to build the virtualbox dkms modules.
If you have the same troubles with the vanilla 4.13 kernel this is not related to the amdgpu display code and I probably can't help you any further.

**Comment by Tormund1985** [comment]
Should I purge Virtualbox and install it after the kernel?
Thanks.

**Comment by M-Bab** [comment]
You can try but I would be surprised if it solves the problem. DKMS modules should not be able to make the kernel crash. Especially if they are not built anyway. And you another piece of software (ndiswrapper) that tries to build dkms modules).
