### ISSUE TITLE
clinfo: Segmentation fault

### ISSUE THREAD

**Issue by rhlug** [M-Bab/linux-kernel-amdgpu-binaries#30]
Fresh install of 17.04, installed the 4.12.14+ ubuntu kernel and firmware packages, and installed rocm-opencl rocm-opencl-dev packages.  

$ /opt/rocm/opencl/bin/x86_64# uname -a 
Linux localhost 4.12.14+ #1 SMP Wed Sep 20 21:21:54 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux

$ /opt/rocm/opencl/bin/x86_64# lspci | grep VGA
23:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480] (rev cf)

$ /opt/rocm/opencl/bin/x86_64# ./clinfo 
Segmentation fault (core dumped)

Not sure how to proceed.

**Comment by dualbus** [comment]
On Thu, Oct 05, 2017 at 01:11:35PM +0000, rhlug wrote:
[...]
> # /opt/rocm/opencl/bin/x86_64# ./clinfo 
> Segmentation fault (core dumped)
> 
> Not sure how to proceed.

You can try generating a backtrace (https://wiki.ubuntu.com/Backtrace)
by running clinfo under gdb.

**Comment by rhlug** [comment]
Pretty sure root cause is..

amdgpu 0000:23:00.0: kfd not supported on this ASIC

I tried an RX470, RX570, and RX Vega 64.  All of them generate that in dmesg.    After switching back to 4.11.0-kfd-compute-rocm-rel-1.6-148 kernel, I have no problems.

**Comment by M-Bab** [comment]
Yeah ... ROCm won't work with this kernel. ROCm is a currently non-mainlined kernel addition just like DC is. I am not sure which Kernel have both patches included - but I am also not sure how stable the result of these 2 heavy-development patch-sets would be.

I am still planning to build a little debian package that provides JUST the opencl libs from the amdgpu-pro driver as a compromise to get DC and OpenCL at the same time.

**Comment by rhlug** [comment]
Okay no problem.  Thanks.
