### ISSUE TITLE
No HDMI Audio

### ISSUE THREAD

**Issue by jonrichards** [M-Bab/linux-kernel-amdgpu-binaries#31]
I really appreciate you putting this repo together, thank you.  I'm running 17.04 with Vega 64.  pavucontrol shows all HDMI audio as unplugged.
````
~$ uname -r
4.13.5+
````
````
~$ dpkg -l firmware\* | awk '$1 == "ii" { print $2 " = " $3}'
firmware-radeon-ucode = 1.50
````
````
~$ dpkg -l mesa\* | awk '$1 == "ii" {print $2 " = " $3}'
mesa-common-dev:amd64 = 1:17.3~git171003222500.d3acc24~z~padoka0
mesa-utils = 8.3.0-4
mesa-va-drivers:amd64 = 17.0.7-0ubuntu0.17.04.1
mesa-vdpau-drivers:amd64 = 1:17.3~git171003222500.d3acc24~z~padoka0
````
Any thoughts on what may be the issue or anything I can try?

**Comment by M-Bab** [comment]
I am sorry to say that but it looks like you did everything right and it still doesn't work.
Did you switch through the HDMI outputs to see if it works anyway (maybe plugin detection doesn't work)? Could you do any cross-check (e.g. with Windows) to ensure the HDMI sound of the GPU and monitor pair works in principle?
You can use the <> button on https://github.com/M-Bab/linux-kernel-amdgpu-binaries/commits/master to download older kernels (maybe try 4.11.12 and 4.12.14) to see if this helps.
Finally you can look through the logs and try to find some hints on the problem.

**Comment by jonrichards** [comment]
I have tried all of the outputs with the same result.  I do know it does work though, as I had it working with this setup on a previous install.  It might be that this time I installed the amdgpu-pro drivers first before switching to amdgpu.  I don't think plugin detection is working though, as if I unplug anything I have to reboot to have it recognized.

Do you have any specific logs you recommend that I should check?

**Comment by M-Bab** [comment]
Did you fully remove the amdgpu-pro driver? It is important that the pro driver is purged otherwise this kernel can't work properly.

Can you post the outputs of: "dmesg | grep amdgpu" and "lsmod | grep amdgpu"

**Comment by DarkFoss** [comment]
@jonrichards You might want to run through your mesa install with dpkg or apt-cache policy and make sure everything related was fully installed. From what you posted your mesa-va-drivers is still stock Ubuntu but the rest show padoka. Check your dpkg log for installation errors during the upgrade. A purge of mesa-va-drivers and reinstalling might help if you see any half-configured messages. I'm not saying it's directly related but nice to rule out.

**Comment by jonrichards** [comment]
@M-Bab I think I got it all removed correctly:
````
~$ dmesg | grep amdgpu
[    1.472800] [drm] amdgpu kernel modesetting enabled.
[    1.476414] fb: switching to amdgpudrmfb from EFI VGA
[    1.476729] amdgpu 0000:43:00.0: Invalid PCI ROM header signature: expecting 0xaa55, got 0xffff
[    1.476773] amdgpu 0000:43:00.0: VRAM: 8176M 0x000000F400000000 - 0x000000F5FEFFFFFF (8176M used)
[    1.476774] amdgpu 0000:43:00.0: GTT: 256M 0x000000F5FF000000 - 0x000000F60EFFFFFF
[    1.476870] [drm] amdgpu: 8176M of VRAM memory ready
[    1.476871] [drm] amdgpu: 8176M of GTT memory ready.
[    1.477112] amdgpu 0000:43:00.0: amdgpu: using MSI.
[    1.477184] [drm] amdgpu: irq initialized.
[    1.477324] amdgpu: [powerplay] amdgpu: powerplay sw initialized
[    1.477546] amdgpu 0000:43:00.0: fence driver on ring 0 use gpu addr 0x000000f5ff400040, cpu addr 0xffffb01110bee040
[    1.477608] amdgpu 0000:43:00.0: fence driver on ring 1 use gpu addr 0x000000f5ff4000c0, cpu addr 0xffffb01110bee0c0
[    1.477640] amdgpu 0000:43:00.0: fence driver on ring 2 use gpu addr 0x000000f5ff400140, cpu addr 0xffffb01110bee140
[    1.477672] amdgpu 0000:43:00.0: fence driver on ring 3 use gpu addr 0x000000f5ff4001c0, cpu addr 0xffffb01110bee1c0
[    1.477703] amdgpu 0000:43:00.0: fence driver on ring 4 use gpu addr 0x000000f5ff400240, cpu addr 0xffffb01110bee240
[    1.477730] amdgpu 0000:43:00.0: fence driver on ring 5 use gpu addr 0x000000f5ff4002c0, cpu addr 0xffffb01110bee2c0
[    1.477760] amdgpu 0000:43:00.0: fence driver on ring 6 use gpu addr 0x000000f5ff400340, cpu addr 0xffffb01110bee340
[    1.477791] amdgpu 0000:43:00.0: fence driver on ring 7 use gpu addr 0x000000f5ff4003c0, cpu addr 0xffffb01110bee3c0
[    1.477819] amdgpu 0000:43:00.0: fence driver on ring 8 use gpu addr 0x000000f5ff400440, cpu addr 0xffffb01110bee440
[    1.477836] amdgpu 0000:43:00.0: fence driver on ring 9 use gpu addr 0x000000f5ff4004e0, cpu addr 0xffffb01110bee4e0
[    1.478209] amdgpu 0000:43:00.0: fence driver on ring 10 use gpu addr 0x000000f5ff400560, cpu addr 0xffffb01110bee560
[    1.478239] amdgpu 0000:43:00.0: fence driver on ring 11 use gpu addr 0x000000f5ff4005e0, cpu addr 0xffffb01110bee5e0
[    1.478513] amdgpu 0000:43:00.0: fence driver on ring 12 use gpu addr 0x000000f4008fa600, cpu addr 0xffffb0111115a600
[    1.478542] amdgpu 0000:43:00.0: fence driver on ring 13 use gpu addr 0x000000f5ff4006e0, cpu addr 0xffffb01110bee6e0
[    1.478567] amdgpu 0000:43:00.0: fence driver on ring 14 use gpu addr 0x000000f5ff400760, cpu addr 0xffffb01110bee760
[    1.478645] amdgpu 0000:43:00.0: fence driver on ring 15 use gpu addr 0x000000f5ff4007e0, cpu addr 0xffffb01110bee7e0
[    1.478669] amdgpu 0000:43:00.0: fence driver on ring 16 use gpu addr 0x000000f5ff400860, cpu addr 0xffffb01110bee860
[    1.478695] amdgpu 0000:43:00.0: fence driver on ring 17 use gpu addr 0x000000f5ff4008e0, cpu addr 0xffffb01110bee8e0
[    1.963161] [drm] amdgpu: freesync_module init done ffff936ca8f996c0.
[    2.000087] Modules linked in: hid_generic(+) usbhid hid amdkfd amd_iommu_v2 mxm_wmi amdgpu(+) crct10dif_pclmul crc32_pclmul ghash_clmulni_intel pcbc aesni_intel aes_x86_64 chash crypto_simd glue_helper ttm cryptd drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops drm igb dca i2c_algo_bit ptp nvme atlantic pps_core nvme_core ahci libahci gpio_amdpt wmi gpio_generic
[    2.000160]  amdgpu_dm_add_sink_to_freesync_module+0x8d/0x1b0 [amdgpu]
[    2.000195]  amdgpu_dm_update_connector_after_detect+0xb9/0x210 [amdgpu]
[    2.000228]  amdgpu_dm_initialize_drm_device+0x350/0x760 [amdgpu]
[    2.000261]  ? mod_freesync_create+0x13e/0x190 [amdgpu]
[    2.000292]  amdgpu_dm_init+0x15f/0x270 [amdgpu]
[    2.000323]  dm_hw_init+0x12/0x20 [amdgpu]
[    2.000347]  amdgpu_device_init+0x1042/0x1700 [amdgpu]
[    2.000372]  amdgpu_driver_load_kms+0x8b/0x2e0 [amdgpu]
[    2.000400]  amdgpu_pci_probe+0x118/0x140 [amdgpu]
[    2.000438]  amdgpu_init+0x91/0xa4 [amdgpu]
[    2.025252] Modules linked in: hid_generic(+) usbhid hid amdkfd amd_iommu_v2 mxm_wmi amdgpu(+) crct10dif_pclmul crc32_pclmul ghash_clmulni_intel pcbc aesni_intel aes_x86_64 chash crypto_simd glue_helper ttm cryptd drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops drm igb dca i2c_algo_bit ptp nvme atlantic pps_core nvme_core ahci libahci gpio_amdpt wmi gpio_generic
[    2.025300]  amdgpu_dm_add_sink_to_freesync_module+0x8d/0x1b0 [amdgpu]
[    2.025329]  amdgpu_dm_update_connector_after_detect+0xb9/0x210 [amdgpu]
[    2.025357]  amdgpu_dm_initialize_drm_device+0x350/0x760 [amdgpu]
[    2.025388]  ? mod_freesync_create+0x13e/0x190 [amdgpu]
[    2.025416]  amdgpu_dm_init+0x15f/0x270 [amdgpu]
[    2.025444]  dm_hw_init+0x12/0x20 [amdgpu]
[    2.025469]  amdgpu_device_init+0x1042/0x1700 [amdgpu]
[    2.025494]  amdgpu_driver_load_kms+0x8b/0x2e0 [amdgpu]
[    2.025521]  amdgpu_pci_probe+0x118/0x140 [amdgpu]
[    2.025556]  amdgpu_init+0x91/0xa4 [amdgpu]
[    2.153074] fbcon: amdgpudrmfb (fb0) is primary device
[    2.153154] amdgpu 0000:43:00.0: fb0: amdgpudrmfb frame buffer device
[    2.184073] amdgpu 0000:43:00.0: ring 0(gfx) uses VM inv eng 3 on hub 0
[    2.184074] amdgpu 0000:43:00.0: ring 1(comp_1.0.0) uses VM inv eng 4 on hub 0
[    2.184074] amdgpu 0000:43:00.0: ring 2(comp_1.1.0) uses VM inv eng 5 on hub 0
[    2.184075] amdgpu 0000:43:00.0: ring 3(comp_1.2.0) uses VM inv eng 6 on hub 0
[    2.184076] amdgpu 0000:43:00.0: ring 4(comp_1.3.0) uses VM inv eng 7 on hub 0
[    2.184077] amdgpu 0000:43:00.0: ring 5(comp_1.0.1) uses VM inv eng 8 on hub 0
[    2.184078] amdgpu 0000:43:00.0: ring 6(comp_1.1.1) uses VM inv eng 9 on hub 0
[    2.184078] amdgpu 0000:43:00.0: ring 7(comp_1.2.1) uses VM inv eng 10 on hub 0
[    2.184079] amdgpu 0000:43:00.0: ring 8(comp_1.3.1) uses VM inv eng 11 on hub 0
[    2.184081] amdgpu 0000:43:00.0: ring 9(kiq_2.1.7) uses VM inv eng 12 on hub 0
[    2.184082] amdgpu 0000:43:00.0: ring 10(sdma0) uses VM inv eng 3 on hub 1
[    2.184083] amdgpu 0000:43:00.0: ring 11(sdma1) uses VM inv eng 4 on hub 1
[    2.184083] amdgpu 0000:43:00.0: ring 12(uvd) uses VM inv eng 5 on hub 1
[    2.184084] amdgpu 0000:43:00.0: ring 13(uvd_enc0) uses VM inv eng 6 on hub 1
[    2.184085] amdgpu 0000:43:00.0: ring 14(uvd_enc1) uses VM inv eng 7 on hub 1
[    2.184086] amdgpu 0000:43:00.0: ring 15(vce0) uses VM inv eng 8 on hub 1
[    2.184087] amdgpu 0000:43:00.0: ring 16(vce1) uses VM inv eng 9 on hub 1
[    2.184088] amdgpu 0000:43:00.0: ring 17(vce2) uses VM inv eng 10 on hub 1
[    2.184572] amdgpu 0000:43:00.0: kfd not supported on this ASIC
[    2.184579] [drm] Initialized amdgpu 3.21.0 20150101 for 0000:43:00.0 on minor 0
[   24.351697] Modules linked in: arc4 rfcomm bnep nls_iso8859_1 edac_mce_amd ath10k_pci ath10k_core btusb kvm ath btrtl snd_hda_codec_realtek btbcm xpad mac80211 btintel irqbypass wil6210 snd_hda_codec_generic ff_memless bluetooth snd_hda_codec_hdmi cfg80211 ecdh_generic snd_seq_midi snd_seq_midi_event snd_hda_intel snd_rawmidi snd_hda_codec snd_hda_core snd_hwdep snd_seq snd_pcm snd_seq_device snd_timer joydev input_leds eeepc_wmi asus_wmi snd sparse_keymap video wmi_bmof ccp soundcore i2c_piix4 shpchp 8250_dw mac_hid parport_pc ppdev lp parport ip_tables x_tables autofs4 algif_skcipher af_alg dm_crypt hid_generic usbhid hid amdkfd amd_iommu_v2 mxm_wmi amdgpu crct10dif_pclmul crc32_pclmul ghash_clmulni_intel pcbc aesni_intel aes_x86_64 chash crypto_simd glue_helper ttm cryptd drm_kms_helper syscopyarea
[   24.351760]  amdgpu_dm_connector_atomic_set_property+0xf4/0x170 [amdgpu]
[   24.351796]  amdgpu_drm_ioctl+0x4f/0x90 [amdgpu]
[   24.351949] Modules linked in: arc4 rfcomm bnep nls_iso8859_1 edac_mce_amd ath10k_pci ath10k_core btusb kvm ath btrtl snd_hda_codec_realtek btbcm xpad mac80211 btintel irqbypass wil6210 snd_hda_codec_generic ff_memless bluetooth snd_hda_codec_hdmi cfg80211 ecdh_generic snd_seq_midi snd_seq_midi_event snd_hda_intel snd_rawmidi snd_hda_codec snd_hda_core snd_hwdep snd_seq snd_pcm snd_seq_device snd_timer joydev input_leds eeepc_wmi asus_wmi snd sparse_keymap video wmi_bmof ccp soundcore i2c_piix4 shpchp 8250_dw mac_hid parport_pc ppdev lp parport ip_tables x_tables autofs4 algif_skcipher af_alg dm_crypt hid_generic usbhid hid amdkfd amd_iommu_v2 mxm_wmi amdgpu crct10dif_pclmul crc32_pclmul ghash_clmulni_intel pcbc aesni_intel aes_x86_64 chash crypto_simd glue_helper ttm cryptd drm_kms_helper syscopyarea
[   24.351993]  amdgpu_dm_connector_atomic_set_property+0xf4/0x170 [amdgpu]
[   24.352044]  amdgpu_drm_ioctl+0x4f/0x90 [amdgpu]
````
````
~$ lsmod | grep amdgpu
amdgpu               2633728  28
chash                  16384  1 amdgpu
ttm                    86016  1 amdgpu
drm_kms_helper        143360  1 amdgpu
drm                   319488  23 amdgpu,ttm,drm_kms_helper
i2c_algo_bit           16384  2 igb,amdgpu
````

**Comment by jonrichards** [comment]
@DarkFoss I did try purging and re-installing mesa-va-drivers, but it doesn't look like it's pulling from padoka.
````
~$ apt-cache policy mesa-va-drivers
mesa-va-drivers:
  Installed: 17.0.7-0ubuntu0.17.04.1
  Candidate: 17.0.7-0ubuntu0.17.04.1
  Version table:
 *** 17.0.7-0ubuntu0.17.04.1 500
        500 http://us.archive.ubuntu.com/ubuntu zesty-updates/universe amd64 Packages
        100 /var/lib/dpkg/status
     17.0.3-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu zesty/universe amd64 Packages
````
However, looking at https://launchpad.net/~paulo-miguel-dias/+archive/ubuntu/mesa/+sourcepub/8353873/+listing-archive-extra I'm not seeing it listed there.  Are you sure it's part of the padoka packages?

**Comment by M-Bab** [comment]
This is odd. It looks like it should (except for DarkFoss' valid comment). But usually it should update all of the mesa package if you add the apt repo - either padoka or oibaf.

Did you test 4.11.12 already? Because 4.12 and 4.13 fight with some regressions that did not exit in the 4.11 kernel.

**Comment by piet8stevens** [comment]
I have also been a grateful user of these custom kernels. I have now found I can play audio over hdmi through my Radeon HD 7700/7800 with the standard 4.13.0-generic kernel on Ubuntu 17.10. What I needed to do was to enable 2 screens in settings/devices/displays - set to 'join displays'. In my case, a Panasonic screen showed up (I only have 1 screen connected to my desktop). When I do that, sound over hdmi/displayport works with the standard kernel. I never tried this on 17.04 so not sure it was the same there. Even with your 4.13.6+ kernel, I get no sound if I only enable the one single screen.

**Comment by piet8stevens** [comment]
I am not sure how the 4.13.6+ kernel generated sound as per my above comment - I have had to go back to your custom kernels in order to have sound. 

One thing I noticed with the custom kernel: if Ubuntu publishes a kernel upgrade, and I install it (but keep using your custom kernel), then my sound on the custom kernel still disappears and I have to reinstall the custom kernel (dpkg).

**Comment by M-Bab** [comment]
Thats an odd case I already experienced before. When you start a "normal" kernel right after a kernel with DC (warm reboot) it still has HDMI sound sometimes. No idea how this works at all. The custom kernel should NOT disappear on Ubuntu kernel updates. Are you sure grub boots the right kernel?

**Comment by piet8stevens** [comment]
Martin, the sound disappears even when I do not reboot. Next time it
disappears, I will try to document it in detail and post here.

Thank you,

Piet

**Comment by M-Bab** [comment]
Can you recheck with 4.17?

**Comment by piet8stevens** [comment]
Well, this is a tough one to check as it is intermittent. Am on 4.17 and will keep an eye on it. For sure, under 4.16.12+, this issue still happened.
uname -r
4.17.2amdgpu.ubuntu.18.06.19+

Thank you for your work!

**Comment by ghost** [comment]
piet make sure to set in your grub amdgpu.dc=1 amdgpu.audio=1 even though the DC code was for vega's its caused muted audio on my system where the hdmi fails. It seems the hdmi audio is entrenched with thre vega code

**Comment by piet8stevens** [comment]
Thx. Will test and report back. Your efforts and M-Bab's are much
appreciated.

**Comment by piet8stevens** [comment]
@tekcomm - I already had amdgpu.dc=1 in grub. Added amdgpu.dc=1. Will see whether I still intermittently lose my sound. So far, so good.
I guess there is still one thing I do not understand: why does amdgpu audio still not work with the generic kernel that comes with ubuntu?

**Comment by ghost** [comment]
Because Murphey's law applies no matter how long mupheys been dead for

**Comment by ghost** [comment]
Uploading
*********************-Rippa CodeX V(egas) 3**********************

Xubuntu 18.04 Bionic
Live memory based system / OpenGL Dev Environment / Playland
Latest X
Amd CodeXL & Pwr kernel module
Latest vega patches & Firmware
Latest AMDGPU Updates & Patches
Steam
Other Extras:
Latest firmware & kernel patches
Dual OpenGL 4.5, Mesa 18.2, AMDPRO OpenGL 2.1 1.2 Vulkan, Clover MesaGL

The Doctor

**Comment by piet8stevens** [comment]
Again lost sound. Still not sure why - cannot remember having made any changes. No problem after reboot.

**Comment by ghost** [comment]
Piet, can you please send me the out put of this script.
https://gist.github.com/craftyjon/902247 amdgpu.dc=1 and amdgpu.audio=1 in
/etc/default/grub

**Comment by piet8stevens** [comment]
@tekcomm  Thank you for all your help. Output of the script is http://www.alsa-project.org/db/?f=07ec5e3fe17a31d1bbf36e671a1b04c0d320582c and also attached. 
[alsa-info 20180703.txt](https://github.com/M-Bab/linux-kernel-amdgpu-binaries/files/2159192/alsa-info.20180703.txt)

Finally, I can confirm that amdgpu.dc=1 and amdgpu.audio=1 are in my /etc/default/grub: 
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash amdgpu.dc=1 amdgpu.audio=1"

Note: the output of the script was generated when sound worked again after reboot. Next time when I lose sound, I will also run the script.

**Comment by piet8stevens** [comment]
And this is the output after having lost sound: http://www.alsa-project.org/db/?f=ab67667e699bb5ef98ac9b88a5c66bc0c86aa770

**Comment by ghost** [comment]
Great I will look at it this weekend, can you try the live cd and let me
know if the audio is working :)
https://drive.google.com/file/d/18ccS5X7r8ue71xUZrP6QCwX5KtdPlre_/view?usp=sharing

**Comment by ghost** [comment]
https://drive.google.com/open?id=1u4Yka0YjRBtyyeHBfkpFpKSCcBCFq8RS

Lol the other link is the amd rocm 1.8.2 and tdxminer/crytonight addon this
is the main dd live usb link

**Comment by ghost** [comment]
Here is the github thread
https://github.com/RadeonOpenCompute/ROCm/issues/361

**Comment by ghost** [comment]
Can you please try this, I had a similar problem with paulo's ppa
ppa-purge it and switch to the https://launchpad.net/~oibaf 
Another more serious problem that affects us all is the erratic behavior I have had with the main repositories failing and even I did not notice, till everything turned black. Try also switching from the main repo to a local mirror.

**Comment by piet8stevens** [comment]
Sorry about the delay. Have had very busy weeks. Will only be able to test in about 10 days' time.

**Comment by M-Bab** [comment]
Should be resolved. Close until there are contradicting comments.

**Comment by piet8stevens** [comment]
I am now on 4.18.8 (uname -r). I installed the ubuntu kernel. Sound is there originally and still disappears after some time.
Sound comes back after reboot. I do need to switch from joint display to 1 display and back for the sound to re-appear.

**Comment by piet8stevens** [comment]
Maybe I found a solution: I added my user to the audio group. Now, I no longer seem to be losing my sound..
