### ISSUE TITLE
Problem after turning screen off and on

### ISSUE THREAD

**Issue by DaGeRe** [M-Bab/linux-kernel-amdgpu-binaries#32]
While the kernel in general works good and provides HDMI audio support for Radeon RX 480, I had an problem when turning my screen on and off again. After I turned it back on, it only recognizes the first screen (connected via DVI), but the second, HDMI-screen couldn't be connected.

Syslog contains:

> Oct 10 10:25:42 reichelt-desktop unity-settings-[2097]: Failed to load PNP ids: Datei »/usr/share/hwdata/pnp.ids« konnte nicht geöffnet werden: Datei oder Verzeichnis nicht gefunden
> Oct 10 10:25:42 reichelt-desktop unity-settings-[2097]: unable to get EDID for xrandr-HDMI-A-0: unable to get EDID for output
> Oct 10 10:25:42 reichelt-desktop unity-settings-[2097]: Failed to load PNP ids: Datei »/usr/share/hwdata/pnp.ids« konnte nicht geöffnet werden: Datei oder Verzeichnis nicht gefunden
> Oct 10 10:25:56 reichelt-desktop kernel: [152337.804363] [drm] Atomic commit: RESET. crtc id 1:[ffff89eb94303000]
> Oct 10 10:25:56 reichelt-desktop kernel: [152337.804367] [drm] dc_commit_state: 1 streams
> Oct 10 10:25:56 reichelt-desktop kernel: [152337.804371] [drm] core_stream 0x52e46c00: src: 0, 0, 3440, 1440; dst: 0, 0, 3440, 1440, colorSpace:1
> Oct 10 10:25:56 reichelt-desktop kernel: [152337.804373] [drm]  pix_clk_khz: 319750, h_total: 3600, v_total: 1481, pixelencoder:1, displaycolorDepth:2
> Oct 10 10:25:56 reichelt-desktop kernel: [152337.804375] [drm]  sink name: , serial: 0
> Oct 10 10:25:56 reichelt-desktop kernel: [152337.804376] [drm]  link: 3
> Oct 10 10:25:56 reichelt-desktop kernel: [152337.842378] [drm] [Mode]   [Virtual][ConnIdx:3] {3440x1440, 3600x1481@319750Khz}^
> Oct 10 10:25:56 reichelt-desktop kernel: [152337.842405] [drm] Atomic commit: RESET. crtc id 1:[ffff89eb94303000]
> Oct 10 10:25:56 reichelt-desktop kernel: [152337.844733] [drm] Atomic commit: RESET. crtc id 0:[ffff89eb94305000]
> Oct 10 10:25:56 reichelt-desktop kernel: [152337.844736] [drm] dc_commit_state: 0 streams
> Oct 10 10:25:56 reichelt-desktop kernel: [152337.874297] [drm] Atomic commit: RESET. crtc id 0:[ffff89eb94305000]
> Oct 10 10:25:56 reichelt-desktop kernel: [152337.884963] [drm] Atomic commit: SET crtc id 1: [ffff89eb94303000]
> Oct 10 10:25:56 reichelt-desktop kernel: [152337.884966] [drm] dc_commit_state: 1 streams
> Oct 10 10:25:56 reichelt-desktop kernel: [152337.884967] [drm] core_stream 0x81f54800: src: 0, 0, 1920, 1080; dst: 0, 0, 1920, 1080, colorSpace:1
> Oct 10 10:25:56 reichelt-desktop kernel: [152337.884968] [drm]  pix_clk_khz: 148500, h_total: 2200, v_total: 1125, pixelencoder:1, displaycolorDepth:2
> Oct 10 10:25:56 reichelt-desktop kernel: [152337.884969] [drm]  sink name: ASUS VH242, serial: 16843009
> Oct 10 10:25:56 reichelt-desktop kernel: [152337.884970] [drm]  link: 4
> Oct 10 10:25:56 reichelt-desktop kernel: [152337.886294] [drm] [Mode]   [DDVI][ConnIdx:4] {1920x1080, 2200x1125@148500Khz}^
> Oct 10 10:25:56 reichelt-desktop unity-settings-[2097]: message repeated 4 times: [ Failed to load PNP ids: Datei »/usr/share/hwdata/pnp.ids« konnte nicht geöffnet werden: Datei oder Verzeichnis nicht gef
> unden]
> Oct 10 10:25:56 reichelt-desktop unity-settings-[2097]: unable to get EDID for xrandr-HDMI-A-0: unable to get EDID for output
> Oct 10 10:25:56 reichelt-desktop unity-settings-[2097]: Failed to load PNP ids: Datei »/usr/share/hwdata/pnp.ids« konnte nicht geöffnet werden: Datei oder Verzeichnis nicht gefunden
> Oct 10 10:25:56 reichelt-desktop unity-settings-[2097]: unable to get EDID for xrandr-HDMI-A-0: unable to get EDID for output
> Oct 10 10:25:56 reichelt-desktop unity-settings-[2097]: Failed to load PNP ids: Datei »/usr/share/hwdata/pnp.ids« konnte nicht geöffnet werden: Datei oder Verzeichnis nicht gefunden
> Oct 10 10:25:56 reichelt-desktop unity-settings-[2097]: unable to get EDID for xrandr-HDMI-A-0: unable to get EDID for output
> Oct 10 10:25:56 reichelt-desktop unity-settings-[2097]: Failed to load PNP ids: Datei »/usr/share/hwdata/pnp.ids« konnte nicht geöffnet werden: Datei oder Verzeichnis nicht gefunden
> Oct 10 10:25:56 reichelt-desktop unity-settings-[2097]: unable to get EDID for xrandr-HDMI-A-0: unable to get EDID for output
> Oct 10 10:25:56 reichelt-desktop unity-settings-[2097]: Failed to load PNP ids: Datei »/usr/share/hwdata/pnp.ids« konnte nicht geöffnet werden: Datei oder Verzeichnis nicht gefunden

And dmesg is: https://nopaste.xyz/?96c1255cad2655b6#BfSeqJjkLUHEfV6d6l/cCTSVidaXobFlZirVOAEx74o=

Is this an known issue?

**Comment by M-Bab** [comment]
Hmmm ... could be related to https://github.com/M-Bab/linux-kernel-amdgpu-binaries/issues/29
Does this issue also exist with the 4.9+ kernel? And the 4.11.12+ kernel from https://github.com/M-Bab/linux-kernel-amdgpu-binaries/tree/54c664461cf5ff19a242d09429f62f38207bd2ea ?

**Comment by DaGeRe** [comment]
I had the 4.12.14+ kernel before, there it existed, and now after the update to 4.13.5+, it exists as well.
Another dmesg: https://nopaste.xyz/?53f0a3b00da96f42#rbVuypUAQ53KaSX/1zmXZ25xNdllIeIF59YgvaXpAGA=
Unfortunately, the error only occurs after turning off the monitor for some time, e.g. over night, and not, if I just switch it off and on again. While xrandr still finds the other screen, the output is black.

I'll try it with 4.11.12+ kernel this night. I could provide syslog or whatever needed.

**Comment by M-Bab** [comment]
It MIGHT be fixed with the latest 4.13 kernel, as there were several commits related to this.

**Comment by DaGeRe** [comment]
This did not happen with the newest kernel (079910e) on Ubuntu 17.10. Unfortunately, I wasn't able to try it with 4.11.12+ until now.

**Comment by M-Bab** [comment]
Can you confirm that this is fixed now?

**Comment by DaGeRe** [comment]
It did not appear for a week, so I assume it is gone. Else I'll create a new issue.

**Comment by mezcalbert** [comment]
Installed 4.14.0+ yesterday. Booted into it right after. Working as it should.
But then...

First suspend yesterday. First system black out on resume today.. :-(.
