### ISSUE TITLE
Didn't work on Ubuntu 16.04

### ISSUE THREAD

**Issue by songproducer** [M-Bab/linux-kernel-amdgpu-binaries#33]
I got some error about not being able to install firmware-radeon-ucode_1.50_all.deb

Now I'm trying to upgrade to 17 but get this:

> W:The repository 'http://repo.radeon.com/rocm/apt/debian zesty Release' does not have a Release file., W:Data from such a repository can't be authenticated and is therefore potentially dangerous to use., W:See apt-secure(8) manpage for repository creation and user configuration details., E:Failed to fetch http://repo.radeon.com/rocm/apt/debian/dists/zesty/main/binary-amd64/Packages  404  Not Found, E:Some index files failed to download. They have been ignored, or old ones used instead.

Any help would be appreciated!

**Comment by M-Bab** [comment]
Hi,

At first: I am curious which error message stopped you from installing the firmware deb package? Do you still have the error message?

Concerning your current issue when upgrading to 17: This error is in no way related to the linux kernel and packages from this page. It looks like you added the rocm (radeon open compute module) apt repository to your system but made some mistake. Look in apt sources /etc/apt/sources.list and /etc/apt/sources.list.d for the faulty entry. But basically such an issue should not stop the upgrade.

**Comment by songproducer** [comment]
I managed to revert to the normal kernel and upgrade to 17.04 (edit)

I just tried again and got the same error:

Errors were encountered while processing:
 firmware-radeon-ucode_1.50_all.deb

https://pastebin.com/raw/Pb2f49dq

**Comment by M-Bab** [comment]
Thanks for posting this error log. This system looks a bit messy to be honest. There is either installed or remnants of:
- amdgpu-pro driver
- AMD ROCM
- this amdgpu dc kernel

They should not be mixed because they are not really compatible to each other. What messes up the installation of the inofficial firmware package is the installed inofficial compute-firmware from ROCM. You could just uninstall compute-firmware then the debian package should install.
But I really recommend to purge the amdgpu-pro driver and the AMD ROCM stuff if you want to use the amdgpu dc kernel.

**Comment by lillelilje** [comment]
Using it without any issues on 16.04 - both the vanilla and ubuntu kernels. :) Just to make sure M-bab doesn't think it's broken for Ubuntu 16.04 itself

**Comment by eelstrebor** [comment]
Wouldn't install on ubuntu 16.04.3:

dpkg-deb: error: 'linux-headers-4.13.6+_17.10.13.AMDGPU_amd64.deb' is not a debian format archive
dpkg: error processing archive linux-headers-4.13.6+_17.10.13.AMDGPU_amd64.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
dpkg-deb: error: 'linux-headers-4.13.6+_17.10.13.AMDGPU.UBUNTU_amd64.deb' is not a debian format archive
dpkg: error processing archive linux-headers-4.13.6+_17.10.13.AMDGPU.UBUNTU_amd64.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
dpkg-deb: error: 'linux-image-4.13.6+_17.10.13.AMDGPU_amd64.deb' is not a debian format archive
dpkg: error processing archive linux-image-4.13.6+_17.10.13.AMDGPU_amd64.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
dpkg-deb: error: 'linux-image-4.13.6+_17.10.13.AMDGPU.UBUNTU_amd64.deb' is not a debian format archive
dpkg: error processing archive linux-image-4.13.6+_17.10.13.AMDGPU.UBUNTU_amd64.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 linux-headers-4.13.6+_17.10.13.AMDGPU_amd64.deb
 linux-headers-4.13.6+_17.10.13.AMDGPU.UBUNTU_amd64.deb
 linux-image-4.13.6+_17.10.13.AMDGPU_amd64.deb
 linux-image-4.13.6+_17.10.13.AMDGPU.UBUNTU_amd64.deb

**Comment by M-Bab** [comment]
That sounds pretty severe. Did you ever retried or re-downloaded the deb files? It sounds like the .deb archives are broken and this is completely unknown yet.
Can you try again with 4.14.0+?

**Comment by eelstrebor** [comment]
I just tried 4.14.0+ and got the same problem. Even the firmware 1.60 gave me the same error message. I'm thinking that I'm doing something wrong but I'm not doing anything different than I did for 4.12.14+ so I don't know what's going on. 4.12.14+ still works fine.

eelstrebor@pavilion:~/Downloads/Linux$ sudo dpkg -i *4.14.0+*
[sudo] password for eelstrebor: 
dpkg-deb: error: 'linux-headers-4.14.0+_17.11.13.AMDGPU_amd64.deb' is not a debian format archive
dpkg: error processing archive linux-headers-4.14.0+_17.11.13.AMDGPU_amd64.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
dpkg-deb: error: 'linux-headers-4.14.0+_17.11.13.AMDGPU.UBUNTU_amd64.deb' is not a debian format archive
dpkg: error processing archive linux-headers-4.14.0+_17.11.13.AMDGPU.UBUNTU_amd64.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
dpkg-deb: error: 'linux-image-4.14.0+_17.11.13.AMDGPU_amd64.deb' is not a debian format archive
dpkg: error processing archive linux-image-4.14.0+_17.11.13.AMDGPU_amd64.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
dpkg-deb: error: 'linux-image-4.14.0+_17.11.13.AMDGPU.UBUNTU_amd64.deb' is not a debian format archive
dpkg: error processing archive linux-image-4.14.0+_17.11.13.AMDGPU.UBUNTU_amd64.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 linux-headers-4.14.0+_17.11.13.AMDGPU_amd64.deb
 linux-headers-4.14.0+_17.11.13.AMDGPU.UBUNTU_amd64.deb
 linux-image-4.14.0+_17.11.13.AMDGPU_amd64.deb
 linux-image-4.14.0+_17.11.13.AMDGPU.UBUNTU_amd64.deb
eelstrebor@pavilion:~/Downloads/Linux$ sudo dpkg -i firmware-radeon-ucode_1.60_all.deb
dpkg-deb: error: 'firmware-radeon-ucode_1.60_all.deb' is not a debian format archive
dpkg: error processing archive firmware-radeon-ucode_1.60_all.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 firmware-radeon-ucode_1.60_all.deb

**Comment by M-Bab** [comment]
Can you check the md5 sum?
cce7da4ae329d6b328d3216f9cfe9026  firmware-radeon-ucode_1.60_all.deb

**Comment by eelstrebor** [comment]
eelstrebor@server1:~/Downloads/Linux$md5sum firmware-radeon-ucode_1.60_all.deb
2795a5753f89a26920a7126465748b65  firmware-radeon-ucode_1.60_all.deb
eelstrebor@server1:~/Downloads/Linux$ ls -l firmware-radeon-ucode_1.60_all.deb
-rw-rw-r-- 1 eelstrebor eelstrebor 32906 Nov 13 15:00 firmware-radeon-ucode_1.60_all.deb

**Comment by M-Bab** [comment]
Well size and checksum are wrong. Are you sure you downloaded the debian files correctly?
 1204258 Okt 31 17:41 firmware-radeon-ucode_1.60_all.deb

**Comment by eelstrebor** [comment]
Turns out that downloading by clicking on the individual files wasn't the right way to download the files. When I downloaded the zipped files the appropriate files installed OK.
