### ISSUE TITLE
Ubuntu Zesty + Ubuntu Kernel 4.13.6+ Virtualbox Kernel Module build fails

### ISSUE THREAD

**Issue by shadyman112** [M-Bab/linux-kernel-amdgpu-binaries#35]
Used Kernel: 4.13.6+ #2 SMP Fri Oct 13 07:45:43 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux

Hi,
I have installed your kernel (by the way great work!!) and the according header files. However the build of the kernel modules for virtualbox 5.1 is not successful.

MODULE -DRT_OS_LINUX -DIN_RING0 -DIN_RT_R0 -DIN_SUP_R0 -DVBOX -DRT_WITH_VBOX -DVBOX_WITH_HARDENING -Wno-declaration-after-statement -DRT_ARCH_AMD64 -DVBOX_WITH_64_BITS_GUESTS -fno-pie  -DMODULE  -DKBUILD_BASENAME='"SUPR0IdcClient_linux"'  -DKBUILD_MODNAME='"vboxnetflt"' -c -o /tmp/vbox.0/linux/SUPR0IdcClient-linux.o /tmp/vbox.0/linux/SUPR0IdcClient-linux.c
  if [ "-pg" = "-pg" ]; then if [ /tmp/vbox.0/SUPR0IdcClient.o != "scripts/mod/empty.o" ]; then ./scripts/recordmcount  "/tmp/vbox.0/SUPR0IdcClient.o"; fi; fi;
(cat /dev/null;   echo kernel//tmp/vbox.0/vboxnetflt.ko;) > /tmp/vbox.0/modules.order
  if [ "-pg" = "-pg" ]; then if [ /tmp/vbox.0/linux/SUPR0IdcClient-linux.o != "scripts/mod/empty.o" ]; then ./scripts/recordmcount  "/tmp/vbox.0/linux/SUPR0IdcClient-linux.o"; fi; fi;
  if [ "-pg" = "-pg" ]; then if [ /tmp/vbox.0/VBoxNetFlt.o != "scripts/mod/empty.o" ]; then ./scripts/recordmcount  "/tmp/vbox.0/VBoxNetFlt.o"; fi; fi;
In file included from ./include/linux/compat.h:16:0,
                 from ./include/linux/ethtool.h:16,
                 from ./include/linux/netdevice.h:42,
                 from /tmp/vbox.0/linux/VBoxNetFlt-linux.c:31:
./include/linux/if.h:27:54: fatal error: sys/socket.h: Datei oder Verzeichnis nicht gefunden (=> file or directory not found)
 #include <sys/socket.h>   /* for struct sockaddr.  */
                                                      ^
compilation terminated.

Any suggestion how to solve or a work around for this problem?

Thanks

**Comment by sp82** [comment]
Have you installed the linux-headers deb?

**Comment by shadyman112** [comment]
Yes, of course:
ii  linux-headers-4.13.5+                           17.10.06.AMDGPU.UBUNTU                                   amd64        Header files related to Linux kernel, specifically,
ii  linux-image-4.13.5+                             17.10.06.AMDGPU.UBUNTU                                   amd64        Linux kernel binary image for version 4.13.5+

**Comment by shadyman112** [comment]
Yes, of course:
# dpkg -l | grep AMDGPU
ii  linux-headers-4.13.5+                           17.10.06.AMDGPU.UBUNTU                                   amd64        Header files related to Linux kernel, specifically,
ii  linux-image-4.13.5+

**Comment by sp82** [comment]
It's look like virtualbox do not support 4.13.
Are you on the last version of virtualbox?
Anyway in the last 2 week a moved to this kernel: https://www.phoronix.com/scan.php?page=news_item&px=AMDGPU-DC-2-Ubuntu-Kernel
and I have virtualbox functioning on Ubuntu 17.10.
EDIT: Sorry not the one  currently on the phoronix website, an older one:  4.13.0-rc5-phx-amdgpu-dc-2 no more available on the website.

**Comment by M-Bab** [comment]
Looks like it is a general problem between kernel 4.13 and virtualbox. Keep updating virtualbox maybe it gets fixed.
