### ISSUE TITLE
Sound crashing from time to time

### ISSUE THREAD

**Issue by DaGeRe** [M-Bab/linux-kernel-amdgpu-binaries#36]
From time to time, the music Ubuntu is playing over RX480 and HDMI (LG Monitor 34UM88C-P.AEU)  contains noise (which shouldn't be there). /var/log/syslog contains:

Nov  7 12:59:31 reichelt-desktop gnome-shell[19453]: Some code accessed the property 'discreteGpuAvailable' on the module 'appDisplay'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Nov  7 12:59:31 reichelt-desktop gnome-shell[19453]: Some code accessed the property 'WindowPreviewMenuItem' on the module 'windowPreview'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Nov  7 13:00:41 reichelt-desktop konqbrowser.desktop[20768]: [1:1:1107/130041.698685:ERROR:render_media_log.cc(25)] MediaEvent: PIPELINE_ERROR audio renderer: output device reported an error
Nov  7 13:00:41 reichelt-desktop rtkit-daemon[1216]: Successfully made thread 27004 of process 27004 (n/a) owned by '1000' high priority at nice level -11.
Nov  7 13:00:41 reichelt-desktop rtkit-daemon[1216]: Supervising 1 threads of 1 processes of 1 users.
Nov  7 13:00:41 reichelt-desktop rtkit-daemon[1216]: Supervising 1 threads of 1 processes of 1 users.
Nov  7 13:00:41 reichelt-desktop rtkit-daemon[1216]: Successfully made thread 27008 of process 27004 (n/a) owned by '1000' RT at priority 5.
Nov  7 13:00:41 reichelt-desktop rtkit-daemon[1216]: Supervising 2 threads of 1 processes of 1 users.
Nov  7 13:00:42 reichelt-desktop rtkit-daemon[1216]: Supervising 2 threads of 1 processes of 1 users.
Nov  7 13:00:42 reichelt-desktop rtkit-daemon[1216]: Successfully made thread 27009 of process 27004 (n/a) owned by '1000' RT at priority 5.
Nov  7 13:00:42 reichelt-desktop rtkit-daemon[1216]: Supervising 3 threads of 1 processes of 1 users.
Nov  7 13:00:42 reichelt-desktop rtkit-daemon[1216]: Supervising 3 threads of 1 processes of 1 users.
Nov  7 13:00:42 reichelt-desktop rtkit-daemon[1216]: Successfully made thread 27010 of process 27004 (n/a) owned by '1000' RT at priority 5.
Nov  7 13:00:42 reichelt-desktop rtkit-daemon[1216]: Supervising 4 threads of 1 processes of 1 users.
Nov  7 13:00:42 reichelt-desktop dbus[770]: [system] Activating via systemd: service name='org.bluez' unit='dbus-org.bluez.service'
Nov  7 13:00:42 reichelt-desktop rtkit-daemon[1216]: Successfully made thread 27012 of process 27012 (n/a) owned by '1000' high priority at nice level -11.
Nov  7 13:00:42 reichelt-desktop rtkit-daemon[1216]: Supervising 5 threads of 2 processes of 1 users.
Nov  7 13:00:42 reichelt-desktop pulseaudio[27012]: [pulseaudio] pid.c: Daemon already running.
Nov  7 13:00:43 reichelt-desktop rtkit-daemon[1216]: Successfully made thread 27018 of process 27018 (n/a) owned by '1000' high priority at nice level -11.
Nov  7 13:00:43 reichelt-desktop rtkit-daemon[1216]: Supervising 1 threads of 1 processes of 1 users.
Nov  7 13:00:43 reichelt-desktop rtkit-daemon[1216]: Supervising 1 threads of 1 processes of 1 users.
Nov  7 13:00:43 reichelt-desktop rtkit-daemon[1216]: Successfully made thread 27020 of process 27018 (n/a) owned by '1000' RT at priority 5.
Nov  7 13:00:43 reichelt-desktop rtkit-daemon[1216]: Supervising 2 threads of 1 processes of 1 users.
Nov  7 13:00:44 reichelt-desktop rtkit-daemon[1216]: Supervising 2 threads of 1 processes of 1 users.
Nov  7 13:00:44 reichelt-desktop rtkit-daemon[1216]: Successfully made thread 27021 of process 27018 (n/a) owned by '1000' RT at priority 5.
Nov  7 13:00:44 reichelt-desktop rtkit-daemon[1216]: Supervising 3 threads of 1 processes of 1 users.
Nov  7 13:00:44 reichelt-desktop rtkit-daemon[1216]: Supervising 3 threads of 1 processes of 1 users.
Nov  7 13:00:44 reichelt-desktop rtkit-daemon[1216]: Successfully made thread 27022 of process 27018 (n/a) owned by '1000' RT at priority 5.
Nov  7 13:00:44 reichelt-desktop rtkit-daemon[1216]: Supervising 4 threads of 1 processes of 1 users.
Nov  7 13:00:44 reichelt-desktop rtkit-daemon[1216]: Successfully made thread 27024 of process 27024 (n/a) owned by '1000' high priority at nice level -11.
Nov  7 13:00:44 reichelt-desktop rtkit-daemon[1216]: Supervising 5 threads of 2 processes of 1 users.
Nov  7 13:00:44 reichelt-desktop pulseaudio[27024]: [pulseaudio] pid.c: Daemon already running.
Nov  7 13:00:44 reichelt-desktop rtkit-daemon[1216]: Successfully made thread 27027 of process 27027 (n/a) owned by '1000' high priority at nice level -11.
Nov  7 13:00:44 reichelt-desktop rtkit-daemon[1216]: Supervising 5 threads of 2 processes of 1 users.
Nov  7 13:00:44 reichelt-desktop pulseaudio[27027]: Daemon already running.

After running pulseaudio -k and pulseaudio -D music is running normal again. This does not happen when I am using the normal PC speakers (via headphone jack).

I am using the latest kernel on Ubuntu 17.10 (but this also happened in Ubuntu 17.04 with older kernels - but with mainline kernel, sound via HDMI did not work at all). Is this a known issue, and is it caused by the kernel or by pulse? Is there a workaround (besides restarting)? If needed, I can get additional logs etc.

**Comment by M-Bab** [comment]
This is a new issue to me. Before I do a lot of guessing, can you test the 4.14 kernel?
