### ISSUE TITLE
Desktop Crashing in Ubuntu 17.10

### ISSUE THREAD

**Issue by DaGeRe** [M-Bab/linux-kernel-amdgpu-binaries#37]
Since my update to ubuntu 17.10, my gnome session is crashing everytime I lock the session and turn off the screen. https://www.nopaste.xyz/?b76a1d79191b2c5b#Gy5W5YlXS8/bpFXvmIQ0JXIdp0gX7TXGI0Byaz8AzB0= shows the syslog.

This is not happening if I just lock the screen, without turning off the monitors, and it toes not happen with linux-image-4.13.0-16-generic.

**Comment by M-Bab** [comment]
This is most likely just the same bug as https://github.com/M-Bab/linux-kernel-amdgpu-binaries/issues/29 but in a slightly different shape.

**Comment by M-Bab** [comment]
Should be fixed with the latest kernel.
