### ISSUE TITLE
Ubuntu 17.10: multihead xrandr and gamma issues

### ISSUE THREAD

**Issue by aubade** [M-Bab/linux-kernel-amdgpu-binaries#39]
Hi! I've got a R9 285, and I've got a couple issues that seem tied to multihead (I've got two identical monitors, both running at 1600x1200@60hz; the first is that setting display gamma doesn't seem to work until I switch to another VT with ctrl-alt-fkeys and back to the X server, which means f.lux and redshift don't work particularly well

The second of which is that anything that changes the video mode renders one of the video outputs non-functional; Usually it's the non-primary head, though it has occasionally been the primary. Further attempts to manually set the video mode on the nonfunctional head or turning it on and off though xrandr don't change anything; only a reboot fixes it. I have a similar problem when the displays go to sleep due to the system being idle.

**Comment by aubade** [comment]
(incidentally, in the vanilla kernel that came with the Ubuntu 17.10 distro that I'm running, multihead wouldn't function at all; the secondary head was just always non-functional)

**Comment by M-Bab** [comment]
Can you try again with the new kernel?

**Comment by aubade** [comment]
Works for Me Now™! Thanks for your work on this.

I'm occasionally getting some bright flashes when redshift is on, but I'm not sure if that's a problem with the AMD drivers, a glitch in redshift, or a localized system issue with something fighting redshift for gamma control.
