### ISSUE TITLE
Crash When Changing Main Screen

### ISSUE THREAD

**Issue by DaGeRe** [M-Bab/linux-kernel-amdgpu-binaries#40]
When I changed the main screen in the graphical menue under Xorg on Ubuntu 17.10, the following log appeared and I could not click anywhere: https://nopaste.xyz/?937371044f0eef7b#7tf2gFqcXBhBnmPmi5xf/mjqcUltyqitHKztQffVkfc= After some minutes, the screen worked again.

May this be a kernel issue, or is this rather a Xorg issue?

**Comment by M-Bab** [comment]
Can you try again with the new kernel?

**Comment by DaGeRe** [comment]
While the first main-screen-change worked, the second led to

> Dec 12 10:06:40 reichelt-desktop systemd[1]: Started Message of the Day.
> Dec 12 10:09:29 reichelt-desktop gnome-shell[1973]: Failed to apply DRM plane transform 0: Das Argument ist ungültig
> Dec 12 10:09:29 reichelt-desktop gnome-shell[1973]: Failed to apply DRM plane transform 0: Das Argument ist ungültig
> Dec 12 10:09:29 reichelt-desktop gnome-shell[1973]: JS WARNING: [resource:///org/gnome/shell/ui/workspaceThumbnail.js 892]: reference to undefined property "_switchWorkspaceNotifyId"
> Dec 12 10:09:29 reichelt-desktop gnome-shell[1973]: WARNING: addSignalMethods is replacing existing [0x55e9ae4133c0 Gjs_ShowAppsIcon.dash-item-container] connect method
> Dec 12 10:09:29 reichelt-desktop gnome-shell[1973]: WARNING: addSignalMethods is replacing existing [0x55e9ae4133c0 Gjs_ShowAppsIcon.dash-item-container] disconnect method
> Dec 12 10:09:29 reichelt-desktop gnome-shell[1973]: WARNING: addSignalMethods is replacing existing [0x55e9ae4133c0 Gjs_ShowAppsIcon.dash-item-container] emit method
> Dec 12 10:09:29 reichelt-desktop kernel: [  704.861342] [drm] REG_WAIT taking a while: 10ms in dce_mi_allocate_dmif line:526
> Dec 12 10:09:34 reichelt-desktop gnome-shell[1973]: JS WARNING: [resource:///org/gnome/shell/ui/modalDialog.js 218]: reference to undefined property "GdkX11Screen"
> Dec 12 10:09:39 reichelt-desktop gnome-shell[1973]: Failed to apply DRM plane transform 0: Das Argument ist ungültig
> Dec 12 10:09:39 reichelt-desktop gnome-shell[1973]: Failed to apply DRM plane transform 0: Das Argument ist ungültig
> Dec 12 10:09:39 reichelt-desktop gnome-shell[1973]: WARNING: addSignalMethods is replacing existing [0x55e9ae691440 Gjs_ShowAppsIcon.dash-item-container] connect method
> Dec 12 10:09:39 reichelt-desktop gnome-shell[1973]: WARNING: addSignalMethods is replacing existing [0x55e9ae691440 Gjs_ShowAppsIcon.dash-item-container] disconnect method
> Dec 12 10:09:39 reichelt-desktop gnome-shell[1973]: WARNING: addSignalMethods is replacing existing [0x55e9ae691440 Gjs_ShowAppsIcon.dash-item-container] emit method
> Dec 12 10:09:39 reichelt-desktop gnome-shell[1973]: Failed to set CRTC mode 1920x1080: Das Argument ist ungültig
> Dec 12 10:09:39 reichelt-desktop gnome-shell[1973]: Failed to flip: Das Gerät oder die Ressource ist belegt
> Dec 12 10:09:39 reichelt-desktop gnome-shell[1973]: Failed to set CRTC mode 1920x1080: Das Argument ist ungültig
> Dec 12 10:09:39 reichelt-desktop gnome-shell[1973]: Failed to set CRTC mode 3440x1440: Das Argument ist ungültig
> Dec 12 10:09:39 reichelt-desktop gnome-shell[1973]: Failed to set CRTC mode 3440x1440: Das Argument ist ungültig
> Dec 12 10:09:39 reichelt-desktop gnome-shell[1973]: Failed to set CRTC mode 1920x1080: Das Argument ist ungültig
> Dec 12 10:09:39 reichelt-desktop gnome-shell[1973]: Failed to set CRTC mode 3440x1440: Das Argument ist ungültig

And many more "Failed to set CRTC mode" (with git hash 079910e Linux reichelt-desktop 4.15.0-rc3+ #1 SMP Mon Dec 11 22:18:10 CET 2017 x86_64 x86_64 x86_64 GNU/Linux). After changing to another terminal, changing back and changing the screen again it worked again.

**Comment by DaGeRe** [comment]
I guess this is related: With 4.15.0-rc3+, after the screen was one night off, it only showed strange stuff and I could not do anything. Therefore, I had to restart the computer by power off.
Syslog contains the following error (so it seems to be the same problem):

> Dec 18 10:13:34 reichelt-desktop gsd-color[2569]: no xrandr-Goldstar Company Ltd-LG ULTRAWIDE-105053 device found: Failed to find output xrandr-Goldstar Company Ltd-LG ULTRAWIDE-105053
> Dec 18 10:13:34 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 1920x1080: Das Argument ist ungültig
> Dec 18 10:13:34 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 1920x1080: Das Argument ist ungültig
> Dec 18 10:13:34 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 3440x1440: Das Argument ist ungültig
> Dec 18 10:13:34 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 3440x1440: Das Argument ist ungültig
> Dec 18 10:13:34 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 1920x1080: Das Argument ist ungültig
> Dec 18 10:13:34 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 3440x1440: Das Argument ist ungültig
> Dec 18 10:13:34 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 1920x1080: Das Argument ist ungültig
> Dec 18 10:13:34 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 3440x1440: Das Argument ist ungültig
> Dec 18 10:13:34 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 1920x1080: Das Argument ist ungültig
> Dec 18 10:13:34 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 3440x1440: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 1920x1080: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 3440x1440: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 1920x1080: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 3440x1440: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 1920x1080: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 3440x1440: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 1920x1080: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 3440x1440: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 1920x1080: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 3440x1440: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 1920x1080: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 3440x1440: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 1920x1080: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 3440x1440: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 1920x1080: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 3440x1440: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 1920x1080: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 3440x1440: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 1920x1080: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 3440x1440: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 1920x1080: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 3440x1440: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 1920x1080: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 3440x1440: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 1920x1080: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 3440x1440: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 1920x1080: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 3440x1440: Das Argument ist ungültig
> Dec 18 10:13:35 reichelt-desktop gnome-shell[2397]: Failed to set CRTC mode 1920x1080: Das Argument ist ungültig

**Comment by M-Bab** [comment]
One night off by using screen lock or how do you disable the screen?
Concerning the screen lock I can confirm the issue (monitor stays black, does not wake up). I guess another regression I have to report to AMD.

**Comment by DaGeRe** [comment]
Yes, one night off.
This happens from time to time, but the last night it did not happen. I'll try this night with rc6 again.

**Comment by M-Bab** [comment]
Can you recheck with 4.17?

**Comment by DaGeRe** [comment]
I am using Ubuntu, and unfortunately, mainline kernel seems to have some problems in Ubuntu: https://askubuntu.com/questions/1027414/build-failed-mainline, https://askubuntu.com/questions/1039201/why-ubuntu-stopped-publishing-signed-linux-kernel-images-since-4-16-4 and https://askubuntu.com/questions/1030043/unable-to-upgrade-kernel-after-4-16-3/1030377#1030377  - basically, any kernel in Ubuntu is unsigned since 4.16.4 and seems to contain bugs, with no reason I know. 
I will try as soon as Ubuntu mainline kernels are usable again. Sorry.

**Comment by M-Bab** [comment]
Should be resolved now.
