### ISSUE TITLE
More than one copy?

### ISSUE THREAD

**Issue by eelstrebor** [M-Bab/linux-kernel-amdgpu-binaries#41]
I get this message even with earlier kernels even though this is the first time installing the package. Why?

More than one copy of package linux-headers-4.15.0-rc3+ has been unpacked in this run !  Only configuring it once.

**Comment by M-Bab** [comment]
Actually no idea. Never seen this before. Is this still the case with rc4 or rc5?

**Comment by M-Bab** [comment]
BTW you should only install the UBUNTU variant or the non-Ubuntu variant. The README is wrong here installing with "dpkg -i *.deb" tries to install two kernels of virtually the same version which results in a conflict.
