### ISSUE TITLE
Random Deactivation of Screen

### ISSUE THREAD

**Issue by DaGeRe** [M-Bab/linux-kernel-amdgpu-binaries#43]
While running Ubuntu 17.10 for some 6 days, it worked (besides some pulse crashs, that could be repaired by restart) fine. Than, without any reason I could think of, one screen was turned of, and then some seconds later turned on again. I was not messing with the wire or something like this.

> Jan 10 17:22:04 reichelt-desktop org.gnome.Shell.desktop[1967]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x31f52dd (Open Resou)
> Jan 10 17:22:07 reichelt-desktop org.gnome.Shell.desktop[1967]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3000347 (dissworksp)
> Jan 10 17:23:19 reichelt-desktop gnome-shell[1967]: Failed to apply DRM plane transform 0: Das Argument ist ungültig
> Jan 10 17:23:20 reichelt-desktop gnome-shell[1967]: WARNING: addSignalMethods is replacing existing [0x562157e0f7f0 Gjs_ShowAppsIcon.dash-item-container] connect method
> Jan 10 17:23:20 reichelt-desktop gnome-shell[1967]: WARNING: addSignalMethods is replacing existing [0x562157e0f7f0 Gjs_ShowAppsIcon.dash-item-container] disconnect method
> Jan 10 17:23:20 reichelt-desktop gnome-shell[1967]: WARNING: addSignalMethods is replacing existing [0x562157e0f7f0 Gjs_ShowAppsIcon.dash-item-container] emit method
> Jan 10 17:23:24 reichelt-desktop gnome-terminal-[2502]: Allocating size to GtkBox 0x560d02b7dc70 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
> Jan 10 17:23:45 reichelt-desktop gnome-shell[1967]: Failed to apply DRM plane transform 0: Das Argument ist ungültig
> Jan 10 17:23:45 reichelt-desktop gnome-shell[1967]: Failed to apply DRM plane transform 0: Das Argument ist ungültig
> Jan 10 17:23:45 reichelt-desktop gnome-shell[1967]: WARNING: addSignalMethods is replacing existing [0x562157da8840 Gjs_ShowAppsIcon.dash-item-container] connect method
> Jan 10 17:23:45 reichelt-desktop gnome-shell[1967]: WARNING: addSignalMethods is replacing existing [0x562157da8840 Gjs_ShowAppsIcon.dash-item-container] disconnect method
> Jan 10 17:23:45 reichelt-desktop gnome-shell[1967]: WARNING: addSignalMethods is replacing existing [0x562157da8840 Gjs_ShowAppsIcon.dash-item-container] emit method
> Jan 10 17:23:47 reichelt-desktop gnome-terminal-[2502]: Allocating size to GtkBox 0x560d02b7dc70 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
> 

I am running 4.15rc6. Could this be a kernel issue or rather a gtk issue?

**Comment by M-Bab** [comment]
There were several issues concerning full screen refreshes and vblanks. My issues disappeared with 4.15.1+ so you are free to try again.

**Comment by DaGeRe** [comment]
This did not appear to me again with 4.15, so I assume the problem is fixed.
