### ISSUE TITLE
amd-staging-4.11 builds?

### ISSUE THREAD

**Issue by Snowman3456** [M-Bab/linux-kernel-amdgpu-binaries#5]
Any plans to prebuild this version?

https://cgit.freedesktop.org/~agd5f/linux/log/?h=amd-staging-4.11

**Comment by M-Bab** [comment]
Yep I decided to support both: 4.9 longterm support and the latest amd-staging which is 4.11 atm. You just caught me too early I detected amd-staging-4.11 just on monday and needed a few tries to build and test it.
