### ISSUE TITLE
4.16.0+ UBUNTU hangs at login (4.16.0-rc7+ did not) on AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx

### ISSUE THREAD

**Issue by m-r-s** [M-Bab/linux-kernel-amdgpu-binaries#52]
When I boot with the UBUNTU version of the 4.16.0+ kernel my HP envy x360 15-bq102ng hangs before Ubuntu 17.10 can be fully loaded.
This is/was not the case with the last RC (4.16.0-rc7+) of the kernel.
I am using the current padoka stable ppa (mesa 18.0.0)

**Comment by mezcalbert** [comment]
I've also had a lot of trouble with padoka ppa (either latest or stable) and amdgpu lately. Could you try with oibaf ppa? 
And if it's stuck, don't hesitate to go to tty (if possible), and either kill Xwayland, gdm, gnome-session or Xorg, this way I usually manage to login after a couple of tries.

**Comment by m-r-s** [comment]
Yes, I can try oibaf later.
I cannot do anything if it's stuck, only press the power button 4s.

**Comment by m-r-s** [comment]
With the oibaf ppa I experience exactly the same behavior.

**Comment by mezcalbert** [comment]
If you purged padoka ppa before trying it, I guess your issue is unrelated to mine then and would need to be solved differently.

**Comment by m-r-s** [comment]
Yes, I purged the padoka ppa with ppa-purge before using the oibaf one.

**Comment by m-r-s** [comment]
I upgraded to Bionic (purged all ppas before) and find still the same behavior

**Comment by M-Bab** [comment]
Do you have any log infos you can provide (like lastlog)?

**Comment by CRTX** [comment]
Just wanted to confirm in that 4.16+ Ubuntu from this repository also has the same behavior with my 2500U. However, if I use the mainline 4.16 kernel my laptop works perfectly fine...

**Comment by m-r-s** [comment]
Here is what I found in /var/log/kern.log
Can I provide anything else which could be interesting?

[kern.log](https://github.com/M-Bab/linux-kernel-amdgpu-binaries/files/1889154/kern.log)

**Comment by m-r-s** [comment]
I can confirm that the latest Ubuntu mainline kernel 4.16.0 (drm-next) works for me as well.

`marc@snapbug:~$ uname -a`
`Linux snapbug 4.16.0-996-generic #201803282201 SMP Thu Mar 29 02:05:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by m-r-s** [comment]
Kernel 4.16.2+ boots again as expected :)
