### ISSUE TITLE
Bug 106159 - When connecting or disconnecting a displayport to a DP hub with 4.16.2+ kernel, hard freeze with frozen video output

### ISSUE THREAD

**Issue by usur-per** [M-Bab/linux-kernel-amdgpu-binaries#54]
Sorry, I thought you were associated with the DRI project at freedesktop.org

https://bugs.freedesktop.org/show_bug.cgi?id=106159

There's a bug report in there.

**Comment by M-Bab** [comment]
You can check again with 4.16.3. I THINK I remember some commits connected with this issue.

**Comment by M-Bab** [comment]
Can you recheck with 4.17?
