### ISSUE TITLE
4.16.2+ lightdm logon screen will not unblank after monitors fall asleep

### ISSUE THREAD

**Issue by usur-per** [M-Bab/linux-kernel-amdgpu-binaries#55]
Again, submitted bug to freedesktop. Here's the link:

https://bugs.freedesktop.org/show_bug.cgi?id=106192

**Comment by M-Bab** [comment]
Thanks for reporting all the stuff upstream at freedesktop. I reported this specific problem already a few times on the amdgpu developers mailing list. I still have hope that this is fixed one day.

**Comment by M-Bab** [comment]
Can you recheck with the latest (4.17)?

**Comment by usur-per** [comment]
I'll need to test this later on. Thanks!

**Comment by M-Bab** [comment]
I think the issue is finally resolved. Didn't see the problem for months.

**Comment by usur-per** [comment]
Hey m-bab. Yeah, you're correct. I'm running 4-17.0+ right now and have not run into the problem since upgrade. Thanks!
