### ISSUE TITLE
When positioning a monitor output above or below initial configuration with xrandr, hard freeze with graphics artifacts 4.16.2+

### ISSUE THREAD

**Issue by usur-per** [M-Bab/linux-kernel-amdgpu-binaries#56]
https://bugs.freedesktop.org/show_bug.cgi?id=106193

Final one I recently posted.

**Comment by M-Bab** [comment]
The patch by Harry proposed on this ISSUE is not yet in amd-staging-drm-next and therefore not in my 4.16.3+

**Comment by M-Bab** [comment]
Can this be closed?

**Comment by usur-per** [comment]
Totally! So sorry, I closed the bug on freedesktop and didn't get this one.
