### ISSUE TITLE
Raven Ridge hangs with VCN 1.45 and 1.73

### ISSUE THREAD

**Issue by brauliobo** [M-Bab/linux-kernel-amdgpu-binaries#57]
I've noticed that this repo uses version 1.45 of `raven_vcn.bin`:
```
[    3.594915] [drm] Found VCN firmware Version: 1.45 Family ID: 18
```

Although the latest version present on `linux-firmware` repo is 1.73 (https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=bd63ccb9d9dd926aa7072f416363dd8f529b5fca).

Both versions hang after a few minutes running `vblank_mode=0 glxgears` on a HP Envy x360 15-bq100.

**Comment by M-Bab** [comment]
Can you try again with the latest kernel + firmware binaries.
I am not aware that there are any newer firmwares for AMD GPUs than on the official build page of AMD. Maybe this "newer" version is due to a different schema of version numbering.

**Comment by marvind** [comment]
The firmware appears to be newer indeed (https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/log/amdgpu/raven_mec2.bin) and it seems to have fixed #48 for me (on 2500U, still testing). 
Also see: https://bugs.freedesktop.org/show_bug.cgi?id=105251#c10

**Comment by M-Bab** [comment]
Could the issue be resolved with the newer kernels and firmware files? Did you install the new mesa drivers? There were a lot of Updates on Raven Ridge.

**Comment by brauliobo** [comment]
`idle=nomwait` actually fixed all hangs
