### ISSUE TITLE
Cant install kernel - 

### ISSUE THREAD

**Issue by nickmaleao** [M-Bab/linux-kernel-amdgpu-binaries#58]
Hello
 
I'm trying to install the kernel packages but i'm getting a error.

ivan@it:~/Downloads/linux-kernel-amdgpu-binaries$ sudo dpkg -i linux-headers-4.16.3+_18.04.23.AMDGPU.UBUNTU_amd64.deb
Selecting previously unselected package linux-headers-4.16.3+.
(Reading database ... 817564 files and directories currently installed.)
Preparing to unpack linux-headers-4.16.3+_18.04.23.AMDGPU.UBUNTU_amd64.deb ...
Unpacking linux-headers-4.16.3+ (18.04.23.AMDGPU.UBUNTU) ...
Setting up linux-headers-4.16.3+ (18.04.23.AMDGPU.UBUNTU) ...
Examining /etc/kernel/header_postinst.d.
run-parts: executing /etc/kernel/header_postinst.d/dkms 4.16.3+ /boot/vmlinuz-4.16.3+
Error! Your kernel headers for kernel 4.16.3+ cannot be found.
Please install the linux-headers-4.16.3+ package,
or use the --kernelsourcedir option to tell DKMS where it's located

Does this kernel packages support dkms? if not, is there a way to compile the kernel with dkms suport?

Ubuntu version:  16.04.4 LTS
Kernel: 4.17.0-rc4-acso

Best regards.

**Comment by M-Bab** [comment]
I assume this is linked to https://github.com/M-Bab/linux-kernel-amdgpu-binaries/issues/60 .
Trying to fix this.

**Comment by ghost** [comment]
Fixed
Please close
