### ISSUE TITLE
Error! Your kernel headers for kernel 4.11.1+ cannot be found

### ISSUE THREAD

**Issue by Snowman3456** [M-Bab/linux-kernel-amdgpu-binaries#6]
Ran `sudo dpkg -i linux-headers-4.11.1+_17.05.17.AMDGPU_amd64.deb linux-image-4.11.1+_17.05.17.AMDGPU_amd64.deb firmware-radeon-ucode_1.10_all.deb`

```
Selecting previously unselected package linux-headers-4.11.1+.
(Reading database ... 508323 files and directories currently installed.)
Preparing to unpack linux-headers-4.11.1+_17.05.17.AMDGPU_amd64.deb ...
Unpacking linux-headers-4.11.1+ (17.05.17.AMDGPU) ...
Selecting previously unselected package linux-image-4.11.1+.
Preparing to unpack linux-image-4.11.1+_17.05.17.AMDGPU_amd64.deb ...
Examining /etc/kernel/preinst.d/
Done.
Unpacking linux-image-4.11.1+ (17.05.17.AMDGPU) ...
Preparing to unpack firmware-radeon-ucode_1.10_all.deb ...
Unpacking firmware-radeon-ucode (1.10) over (1.10) ...
Setting up linux-headers-4.11.1+ (17.05.17.AMDGPU) ...
Examining /etc/kernel/header_postinst.d.
run-parts: executing /etc/kernel/header_postinst.d/dkms 4.11.1+ /boot/vmlinuz-4.11.1+
Error! Your kernel headers for kernel 4.11.1+ cannot be found.
Please install the linux-headers-4.11.1+ package,
or use the --kernelsourcedir option to tell DKMS where it's located
Error! Your kernel headers for kernel 4.11.1+ cannot be found.
Please install the linux-headers-4.11.1+ package,
or use the --kernelsourcedir option to tell DKMS where it's located
Setting up linux-image-4.11.1+ (17.05.17.AMDGPU) ...

 Hmm. There is a symbolic link /lib/modules/4.11.1+/build
 However, I can not read it: No such file or directory
 Therefore, I am deleting /lib/modules/4.11.1+/build


 Hmm. The package shipped with a symbolic link /lib/modules/4.11.1+/source
 However, I can not read the target: No such file or directory
 Therefore, I am deleting /lib/modules/4.11.1+/source
```

**Comment by M-Bab** [comment]
This reminds me of your issue https://github.com/M-Bab/linux-kernel-amdgpu-binaries/issues/4 - read/write errors in /lib/modules. Absolutely sure there is no I/O or permission problem there? Does "ls -l /lib/modules/4.11.1+/" show broken links?

**Comment by M-Bab** [comment]
Okay this might be required to fix broken links: http://forums.debian.net/viewtopic.php?f=10&t=56920

#!/bin/sh
cd /lib/modules/$(uname-r)
rm build
rm source
ln -s /usr/src/linux-headers-$(uname -r) build
ln -s /usr/src/linux-headers-$(uname -r) source

Which requires you be booted into the new kernel to use the $(uname -r) variable correctly. Then rebuild the dkms modules.

**Comment by Snowman3456** [comment]
`ls -l /lib/modules/4.11.1+/` looks fine.

There wasn't a reference for `ln -s /usr/src/linux-headers-$(uname -r) source`.

How do I check/rebuild modules?

**Comment by M-Bab** [comment]
But the kernel should still be properly installed and runnable even if the dkms modules install fails. I dont know concerning VM Ware but virtual box allows to remove/update/reinstall the guest extensions. Concerning a forced reinstall of dkms modules I dare you to google around a bit.

Then you quickly find stuff like this: https://askubuntu.com/questions/53364/command-to-rebuild-all-dkms-modules-for-all-installed-kernels

Good luck!
