### ISSUE TITLE
Graphics doesn't display games

### ISSUE THREAD

**Issue by tome3055** [M-Bab/linux-kernel-amdgpu-binaries#63]
Hi. i am running linux mint 18.1 with kernel 4.16.15+ and i have AMD R7 M445 and the kernel works but sometimes(often in some games) it doesn't display the image.
Ex. Kerbal space program or Dota 2 i get the cursor from the game and window from the game but the game isn't displayed. (Sorry for my bad English)
![screenshot from 2018-06-17 22-26-16](https://user-images.githubusercontent.com/2844888/41511764-8314578c-727d-11e8-99ab-b7aaaac7cacb.png)

**Comment by M-Bab** [comment]
Try to install libegl-mesa0 otherwise it might be possible that games run without hardware acceleration = they run horribly slow or do not run at all.

**Comment by tome3055** [comment]
Yeah, sometimes it run slow and sometimes it didn't run at all. 
Thanks that solved my problem.
