### ISSUE TITLE
linux-headers archives shipped w/o objtool binary

### ISSUE THREAD

**Issue by m-ueberall** [M-Bab/linux-kernel-amdgpu-binaries#64]
Could you please check why the current "linux-headers" archives are missing the equivalent of the original ``linux-headers-*-generic*_<arch>.deb`` contents, including ``/usr/src/linux-headers-*-generic/tools/objtool/objtool`` (this is needed, e.g., if you want to build the zfs .deb packages for the kernel)?

**Comment by m-ueberall** [comment]
Update: If you use ``make deb-pkg`` instead of ``fakeroot make-kpkg``, the resulting linux-headers* .deb archive _does_ contain said binary:
```
$ dpkg -c linux-headers-4.17.2*.deb | grep "objtool$"
-rwxr-xr-x root/root    563880 2018-06-26 18:44 ./usr/src/linux-headers-4.17.2/tools/objtool/objtool
```

**Comment by M-Bab** [comment]
Unfortunately in my case the kernel never built properly with make deb-pkg...

**Comment by M-Bab** [comment]
@m-ueberall What was your command to build the kernel from source with make deb-pkg?

**Comment by m-ueberall** [comment]
@M-Bab I basically followed [_"Compiling a Kernel"_](https://debian-handbook.info/browse/stable/sect.kernel-compilation.html) from _The Debian Administrator's Handbook_ and used the following script on an Intel NUC (hence the `-j8`):
```
#!/bin/sh
BUILD_DATE=yyyymmdd
BUILD_REVISION=1
#BUILD_OPTIONS="INSTALL_MOD_STRIP=1"
BUILD_OPTIONS=""
make -j8 DEBFULLNAME="myname" DEBEMAIL="myemailaddress" EXTRAVERSION=-amdgpu${BUILD_DATE} KDEB_PKGVERSION=$(make kernelversion)-${BUILD_REVISION} ${BUILD_OPTIONS} deb-pkg
```

**Comment by viggy96** [comment]
Has this been resolved? For now my workaround is coping objtool binaries from an older kernel on my system...

**Comment by viggy96** [comment]
Can we please include the objtool binary with these kernels?

**Comment by M-Bab** [comment]
Is fixed now.
