### ISSUE TITLE
lightdm/xorg freeze on boot, kernel=4.18-rc8, cpu=ryzen 3 2200g

### ISSUE THREAD

**Issue by bucketsize** [M-Bab/linux-kernel-amdgpu-binaries#66]
cpu: AMD Ryzen 3 2200G with Radeon Vega Graphics
mainboard: Gigabyte Technology Co., Ltd. A320M-S2H/A320M-S2H-CF, BIOS F22 03/15/2018

- lightdm freezes post background wallpaper, on boot without boot param `nomodeset` everytime.
- startx directly also results in a xorg/gnome freeze just after background wallpaper is loaded.
- graphical startup is proper with boot param `nomodeset`.
- not passing amdgpu.dc=1 as it has no effect.
- using stock ubuntu 18.04lts mesa/graphics drivers.

-- dmesg --
[    2.845933] [drm] amdgpu kernel modesetting enabled.
[    2.969228] fb: switching to amdgpudrmfb from VESA VGA
[    3.004089] amdgpu 0000:07:00.0: VRAM: 1024M 0x000000F400000000 - 0x000000F43FFFFFFF (1024M used)
[    3.004092] amdgpu 0000:07:00.0: GART: 1024M 0x000000F500000000 - 0x000000F53FFFFFFF
[    3.004190] [drm] amdgpu: 1024M of VRAM memory ready
[    3.004192] [drm] amdgpu: 3072M of GTT memory ready.
[    3.196334] amdgpu: [powerplay] dpm has been enabled
[    3.196601] WARNING: CPU: 0 PID: 177 at drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calcs.c:1379 dcn_bw_update_from_pplib+0x19a/0x2b0 [amdgpu]
[    3.196607] Modules linked in: amdkfd amd_iommu_v2 amdgpu(+) chash i2c_algo_bit gpu_sched ttm drm_kms_helper hid_generic syscopyarea sysfillrect r8169 usbhid sysimgblt mii fb_sys_fops i2c_piix4 hid drm ahci libahci wmi gpio_amdpt video gpio_generic
[    3.196740] RIP: 0010:dcn_bw_update_from_pplib+0x19a/0x2b0 [amdgpu]
[    3.196923]  dcn10_create_resource_pool+0x7d4/0x9e0 [amdgpu]
[    3.196989]  dc_create_resource_pool+0x46/0x170 [amdgpu]
[    3.197055]  ? dal_gpio_service_create+0xa1/0x120 [amdgpu]
[    3.197101]  ? dal_gpio_service_create+0xa1/0x120 [amdgpu]
[    3.197145]  dc_create+0x221/0x610 [amdgpu]
[    3.197192]  dm_hw_init+0xc3/0x250 [amdgpu]
[    3.197225]  amdgpu_device_init+0xcfb/0x15d0 [amdgpu]
[    3.197257]  amdgpu_driver_load_kms+0x8b/0x2c0 [amdgpu]
[    3.197299]  amdgpu_pci_probe+0x148/0x200 [amdgpu]
[    3.197378]  amdgpu_init+0x7a/0x89 [amdgpu]
[    3.197767] [drm:construct [amdgpu]] *ERROR* construct: Invalid Connector ObjectID from Adapter Service for connector index:2! type 0 expected 3
[    3.292838] fbcon: amdgpudrmfb (fb0) is primary device
[    3.378976] amdgpu 0000:07:00.0: fb0: amdgpudrmfb frame buffer device
[    3.392100] amdgpu 0000:07:00.0: ring 0(gfx) uses VM inv eng 4 on hub 0
[    3.392140] amdgpu 0000:07:00.0: ring 1(comp_1.0.0) uses VM inv eng 5 on hub 0
[    3.392182] amdgpu 0000:07:00.0: ring 2(comp_1.1.0) uses VM inv eng 6 on hub 0
[    3.392223] amdgpu 0000:07:00.0: ring 3(comp_1.2.0) uses VM inv eng 7 on hub 0
[    3.392265] amdgpu 0000:07:00.0: ring 4(comp_1.3.0) uses VM inv eng 8 on hub 0
[    3.392306] amdgpu 0000:07:00.0: ring 5(comp_1.0.1) uses VM inv eng 9 on hub 0
[    3.392348] amdgpu 0000:07:00.0: ring 6(comp_1.1.1) uses VM inv eng 10 on hub 0
[    3.392389] amdgpu 0000:07:00.0: ring 7(comp_1.2.1) uses VM inv eng 11 on hub 0
[    3.392418] amdgpu 0000:07:00.0: ring 8(comp_1.3.1) uses VM inv eng 12 on hub 0
[    3.392446] amdgpu 0000:07:00.0: ring 9(kiq_2.1.0) uses VM inv eng 13 on hub 0
[    3.392479] amdgpu 0000:07:00.0: ring 10(sdma0) uses VM inv eng 4 on hub 1
[    3.392506] amdgpu 0000:07:00.0: ring 11(vcn_dec) uses VM inv eng 5 on hub 1
[    3.392534] amdgpu 0000:07:00.0: ring 12(vcn_enc0) uses VM inv eng 6 on hub 1
[    3.392561] amdgpu 0000:07:00.0: ring 13(vcn_enc1) uses VM inv eng 7 on hub 1
[    3.392589] amdgpu 0000:07:00.0: ring 14(vcn_jpeg) uses VM inv eng 8 on hub 1
[    3.396636] [drm] Initialized amdgpu 3.27.0 20150101 for 0000:07:00.0 on minor 0

-- xorg summary --
no apparent errors in Xorg.0.conf

**Comment by marvind** [comment]
It is important to have the latest firmware installed on raven (firmware-radeon-ucode_2.10_all.deb). If you already have, you could try a more recent mesa like: https://launchpad.net/%7Epaulo-miguel-dias/+archive/ubuntu/mesa

**Comment by M-Bab** [comment]
@bucketsize could the issue be resolved with the newer kernels and firmware files? Did you install the new mesa drivers?

**Comment by CRTX** [comment]
Pretty sure this is fixed with Kernel 4.19+. I used to get those dmesg dumps until then
