### ISSUE TITLE
4.18.0 and 4.18.8 Intel nic used to work with e1000e

### ISSUE THREAD

**Issue by BobDodds** [M-Bab/linux-kernel-amdgpu-binaries#70]
I upgraded packages unrelated to networking, debconfig package scripts called grub update-initramfs, and then on reboot and ever since, e1000e says it's UP, ifup thinks it's up, but ping does not work.

Pastebin of startup script output, including ethtool, ip addr, plus dmesg: https://pastebin.com/UsF76Z4q

**Comment by BobDodds** [comment]
Temporary [fix:](https://unix.stackexchange.com/a/470414/174552)

ethtool -K eth0 gso off gro off tso off

I don't even know what that does, or if I lose something by doing [that.](https://unix.stackexchange.com/a/470414/174552)

**Comment by BobDodds** [comment]
Linux mainline tip kernel's e1000e has the same prob. Ubuntu desktop kernel does not. I will try Ubuntu lowlatency kernel...

**Comment by M-Bab** [comment]
Is it fixed in 4.19.rc kernel?
