### ISSUE TITLE
Virtuabox Error building the module

### ISSUE THREAD

**Issue by Grillkoenig** [M-Bab/linux-kernel-amdgpu-binaries#72]
Hi all,

First let me say thank you for these excellent binaries - they really take advantage of the latest AMD APUs.  Unfortunately it appears that my know how can not keep up with the challenges that come with such advanced kernels.  I have tried everything to get virtualbox up and running but all my attempts faild with the below error - Any hint how to tackle this would be very much appreciated. Thanks Nick

I am currently using linux-image-4.18.5  and VirtualBox-5.2.19-125724-Linux_amd64.run

`Building the main VirtualBox module.
Error building the module:
make V=1 CONFIG_MODULE_SIG= -C /lib/modules/4.18.5/build SUBDIRS=/tmp/vbox.0 SRCROOT=/tmp/vbox.0 -j8 modules
make[1]: warning: -jN forced in submake: disabling jobserver mode.
mkdir -p /tmp/vbox.0/.tmp_versions ; rm -f /tmp/vbox.0/.tmp_versions/*
make -f ./scripts/Makefile.build obj=/tmp/vbox.0
(cat /dev/null;   echo kernel//tmp/vbox.0/vboxdrv.ko;) > /tmp/vbox.0/modules.order
make[2]: *** No rule to make target '/tmp/vbox.0/linux/SUPDrv-linux.o', needed by '/tmp/vbox.0/vboxdrv.o'.  Stop.
make[2]: *** Waiting for unfinished jobs....
Makefile:1500: recipe for target '_module_/tmp/vbox.0' failed
make[1]: *** [_module_/tmp/vbox.0] Error 2
/tmp/vbox.0/Makefile.include.footer:101: recipe for target 'vboxdrv' failed
make: *** [vboxdrv] Error 2`

**Comment by CRTX** [comment]
Pretty sure VirtualBox needs to be updated to use the newest kernels. I have the same problem with `ZFS` module. Unfortunately you'll need to roll back to an earlier kernel to work with AMDGPU and VirtualBox until VBox is updated to work with 4.18+

**Comment by CRTX** [comment]
https://www.virtualbox.org/wiki/Downloads Virtualbox 5.2.20 supports up to Kernel 4.19 now. Tested using Kernel 4.19rc7. Uninstall your previous virtualbox package and download the new version from the site. I believe issue may be closed

**Comment by Grillkoenig** [comment]
Thanks - for your response - I have moved to to QEMU/KVM in the meantime which does not seem to have any issues. But I will try VB 5.2.20 to have an alternative.
Regards Nick
