### ISSUE TITLE
Not really an issue Amd updated their firmware today

### ISSUE THREAD

**Issue by DarkFoss** [M-Bab/linux-kernel-amdgpu-binaries#73]
From [Phoronix](https://www.phoronix.com/scan.php?page=news_item&px=AMDGPU-Raven-DMCU-FW) 
Hoping you'll have the time for an update :)
Latest kernel is working fine on KDE-Neon(18.04 Ubuntu) previous kernel also worked fine on Neon as well as 18.04 and 18.10 Ubuntu's. 
Great work once again much appreciated!

**Comment by M-Bab** [comment]
Thanks for the info - I will update them soon!

**Comment by DarkFoss** [comment]
Sweet, Thank you.

Just installed 4.19.1-ubuntu flavor it's working great on Kde-Neon feels a bit smoother than 19.0 Dmesg & Syslog look good, using Oibaf's ppa
