### ISSUE TITLE
debian/testing: firmware-radeon-ucode prevents installation of firmware-linux

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [M-Bab/linux-kernel-amdgpu-binaries#75]
> CAUTION: firmware-radeon-ucode*.deb might replace amdgpu firmware files of linux-firmware. So if you remove it you might lose some important blob firmwares. They can be recovered with:

In debian/testing I had to remove firmware-amd-graphics and firmware-linux-nonfree, otherwise I could not install your package. I cannot reinstall firmware-linux because it detects a file conflict and refuses to continue.

on my ASrock B450-HDV with Ryzen3 2200G, your kernel makes the difference between booting every time (thank you, thank you, thank you!) instead of one in five, so it's a keeper but how can I fix the dependencies? Bonus points if I don't run the risk of apt-get autoremove nuking something.

**Comment by M-Bab** [comment]
I updated the firmware package. It says "replaces" now for the packages you mentioned. Can you try again?

**Comment by AndreaBorgia-Abo** [comment]
Yup, it seems to work fine: first I installed your new files, then ran apt-get install for firmware-amd-graphics and firmware-linux-nonfree.
All dependencies were pulled and installed, I'd say it works. Thanks again :)
