### ISSUE TITLE
missing "vanilla" version

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [M-Bab/linux-kernel-amdgpu-binaries#76]
Currently there are only ubuntu-specific prebuilt binaries.
Are the debian / vanilla versions on the way?
If not, where may I find the reference config files to build them myself from the source?

**Comment by M-Bab** [comment]
That was actually a missnaming. It was the vanilla version. But now both kernels are available in 4.20 (so Ubuntu and vanilla variant).
