### ISSUE TITLE
Tag releases ?

### ISSUE THREAD

**Issue by stuaxo** [M-Bab/linux-kernel-amdgpu-binaries#77]
Hi,
   Any chance of using git tags, and maybe using the github releases feature ?
I'd like to experiment with older kernels (e.g. from the ubuntu ppa 4.19.4 works well) but it's not easy to grab them from this repo at the moment.

Cheers
S

**Comment by M-Bab** [comment]
I am thinking about it. Would tag the matching source code at https://github.com/M-Bab/linux-kernel-amdgpu then. But this is quite some effort.

**Comment by stuaxo** [comment]
Maybe just for future releases would be less hassle ?
