### ISSUE TITLE
No releases for 4.19.2 or 4.20 RC

### ISSUE THREAD

**Issue by kushalpandya** [M-Bab/linux-kernel-amdgpu-binaries#79]
Is this project no longer updated? Although Mesa 18.2 is stable now and one can install it from PPA and latest kernel from this Repo in Ubuntu, but AMDGPU support is still missing from stable Ubuntu 18.04. And currently, kernels from this repo are outdated and vulnerable.

**Comment by M-Bab** [comment]
I am still active on this but to be honest the latest builds are not successful. Therefore i decided to wait till amd-staging-drm-next is rebased to kernel 5.0 and then I will do a new release.
