### ISSUE TITLE
5.0rc4 hangs playing video with mpv

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [M-Bab/linux-kernel-amdgpu-binaries#80]
When I play a video with mpv, the system locks up hard: last audio buffer plays on repeat, no mouse, keyboard or network activity any more.
Using 4.20-rc6 this did not happen (debian/testing, Ryzen 2200G, AsRock B450)

**Comment by M-Bab** [comment]
You can try again with 5.0-rc6. I am pushing this right now. And also try a vanilla kernel 5.0-rc6 build. 

If the problem remains in rc6 and does not exist and the vanilla version, I will contact AMD about the issue.

**Comment by AndreaBorgia-Abo** [comment]
Thanks, I haven't yet been able to reproduce the issue with your rc6, but I've forgotten to note which file was it so I must test until I've played all the recent ones. I will update the ticket once I have new information.

**Comment by AndreaBorgia-Abo** [comment]
Lots of videos later, still cannot reproduce with rc6, hence closing.
I'll open a new report with a testcase if and when I can reproduce.
Thanks :)
