### ISSUE TITLE
missing vega20_ta.bin

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [M-Bab/linux-kernel-amdgpu-binaries#82]
update-initramfs: Generating /boot/initrd.img-5.0.4-19.03.25.amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/vega20_ta.bin for module amdgpu

**Comment by OneTinSoldier66** [comment]
Hello Andrea,

I get the same warning. But it’s just a warning(W:), and not an error(E:). I just finished installing this repository on my Debian Buster system with an AMD Radeon VII as my GPU. Then I went into my BIOS and changed it from Windows UEFI mode to Other OS mode(under Secure Boot options).

Then I booted up into the new kernel and was greeted with a graphical lightdm login screen at 4K resolution. Prior to that, I was only getting the command line console.

So, the vega20_ta.bin may only be for one specific GPU and you won’t have any problem, unless it’s the GPU that you have. Or it may be that it enables some feature/functionality or acceleration that would be nice to have, but we won’t get in a Linux kernel until later. But I don’t think it’s needed. It would be nice to know what that firmware binary blob is for, but I don’t know.

**Comment by AndreaBorgia-Abo** [comment]
Yup, I know it's a warning but I'm reporting it on the off chance that somebody might need it. Hopefully @M-Bab knows more about this.

**Comment by M-Bab** [comment]
Hi. The code status and the binary file support does not always match. Often the code is ahead and already ready to include some firmware binary blobs that are not published yet. This was the case for Raven or Vega. I regularly grep the newest blobs from https://people.freedesktop.org/~agd5f/radeon_ucode and https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/amdgpu and package them into the firmware-radeon-ucode which enables the most recent cards. But as you can see neither of them include the vega20_ta.bin file already. I guess it is not essential to have the vega20 running properly. So just ignore the warning and one day when the vega20_ta.bin file is released and included in my debian package the warning will be gone.

**Comment by AlexBakun** [comment]
But there is everything we need... The 1st link has vg20 folder:
https://people.freedesktop.org/~agd5f/radeon_ucode/vg20/
the second one already has vega20... :)
We are lucky :)

**Comment by M-Bab** [comment]
Well yes ... but I already included these files in my firmware package. The unfortunate things is if you look out for it: vega20_ta.bin is also not existing in this folder :/

**Comment by M-Bab** [comment]
Okay I found the firmware binaries: In an debian package for radeon open compute (http://repo.radeon.com/rocm/apt/debian/pool/main/r/rock-dkms/)

If you are brave enough you can test this package:

[firmware-radeon-ucode-rock_2.110_all.deb.zip](https://github.com/M-Bab/linux-kernel-amdgpu-binaries/files/4124959/firmware-radeon-ucode-rock_2.110_all.deb.zip)

It definitely reports less warnings during initramfs creation. If you can use this package without issues I consider packing these blobs to the standard repo contents.

**Comment by regchanuk** [comment]
> Hi. The code status and the binary file support does not always match. Often the code is ahead and already ready to include some firmware binary blobs that are not published yet. This was the case for Raven or Vega. I regularly grep the newest blobs from https://people.freedesktop.org/~agd5f/radeon_ucode and https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/amdgpu and package them into the firmware-radeon-ucode which enables the most recent cards. But as you can see neither of them include the vega20_ta.bin file already. I guess it is not essential to have the vega20 running properly. So just ignore the warning and one day when the vega20_ta.bin file is released and included in my debian package the warning will be gone.

would like to say thank you for this i had upgraded from debian 9 stretch to debian 10 buster files were not included while upgraded
