### ISSUE TITLE
Upgrade firmware ?

### ISSUE THREAD

**Issue by stuaxo** [M-Bab/linux-kernel-amdgpu-binaries#83]
It looks like the firmware has been updated since the version here, is it worth making that match git ?

Looking at raven_dmcu.bin it was updated on 26/November from 23120 bytes (size in the deb from here), to 23152 bytes:

https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/amdgpu/raven_dmcu.bin?id=9200baafe38dc2b1fdce2649a314eede5a39fe6a

**Comment by M-Bab** [comment]
Yep I updated them. I always use two sources for the firmware blobs (linux-firmware.git and https://people.freedesktop.org/~agd5f/radeon_ucode/) to ensure the most recent stuff is onboard. I hope to provide updates more frequently again.

**Comment by stuaxo** [comment]
Awesome :)

Thanks for this PPA.
