### ISSUE TITLE
Virtualbox don't works after kernel 5.2.13

### ISSUE THREAD

**Issue by bakoulis** [M-Bab/linux-kernel-amdgpu-binaries#85]
Virtualbox add support for hosts and guests for kernel 5.5, but after update my Debian kernel 5.2.13, none of the next new kernels run VB. No matter if install VB v5.2, v6.0 or v6.1.4.
Now I have the latest kernel 5.5.10 but must boot on the old 5.2.13 kernel to have VB support and can run a Win10 virtual machine guest.

**Comment by M-Bab** [comment]
Yeah that sucks. I just recently recognized this but had no idea why. However, good news: The 5.6 kernel builds the kernel modules with the default packaged virtualbox on Ubuntu 20.04.
