### ISSUE TITLE
Crash by testing a Blender file.

### ISSUE THREAD

**Issue by MarioMey** [M-Bab/linux-kernel-amdgpu-binaries#86]
Sorry, I know that the intention of this github is to provide the kernel and firmwares, you don't code the kernel nor the firmware... also, I didn't debug it (tell me how to do it if it is necessary), but I want to leave this report here.

- Yesterday I bought a Ryzen 5 3400G + RX Vega 11.
- I just installed this kernel as README.md says.
- I booted and tested some Phoronix benchmarks. What I tested, worked.
- I opened Blender 2.28. Opened wasp_bot.blend (file that comes with Blender). I tested it (rotate the view around the object) and it works very well.
- I opened wanderer.blend (also comes with software). And when waiting to completly load the scene (textures specially), **the computer crash**: blank screen and nothing else. I couldn't enter even in TT1 or TT2.
- Rebooted and tested again. **Crash again**. But now, it was different: blank screen for seconds, screen cames back but cannot interact (can move the mouse but cannot click or use keyboard) for seconds... blank screen, again screen with no interact, blank screen... ad infinitum.

Is there something to do, to test, to debug?

Is possible to do what this kernel does, but manually? I mean, by installing the kernel and the firmware separately and make they work exactly as this github kernel does?

**Comment by MarioMey** [comment]
- I installed AMD firmware from Debian page
- Booted in previous kernel
- Did the same with Blender and, by compiling shaders (75% of this file), it did something similar: blank screen... normal screen... but this time, system didn't hang. I could continue using computer and I could see some errors in Blender console. Haundreds of:

`amdgpu: The CS has been cancelled because the context is lost.`

As google says, this seems a firmware bug.

**Comment by M-Bab** [comment]
Hello! It was time to update the kernel again - so I did. There is also an update on the firmware binaries (20.20). You can try if this helps before we look into further debugging.

**Comment by MarioMey** [comment]
I will try your kernel... but I would want to know where are the firmware binaries, could I?

The Blender crash, as I told you above, with your kernel, made the system crash. I had to boot. Then, I switched to my previous kernel 5.5 and installed firmware with (from this [link](https://wiki.debian.org/AtiHowTo)):

`apt-get install firmware-linux-nonfree libgl1-mesa-dri libglx-mesa0 mesa-vulkan-drivers xserver-xorg-video-all`

So, Blender crashed only the software, I could go on using the system. But yesterday I couldn't go back... and today I could. 🤷

I will keep on testing your kernel, official kernels and firmwares.

**Comment by M-Bab** [comment]
The firmware files are stored in /lib/firmware/amdgpu. My special debian package collects and combines the firmware binaries from https://people.freedesktop.org/~agd5f/radeon_ucode/ with the official linux firmware binaries from https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/amdgpu

**Comment by MarioMey** [comment]
Installed new kernel from this github... but system still hangs with the same file in the same moment of loading and compiling shaders. If it is the only problem of this new brand recently bought computer... is no problem. I'm not creating shaders or making 3d animation.

I will still wait for a fix... some day.

Thanks for the response!

**Comment by M-Bab** [comment]
You can try again with the new kernel. If it does not work we go into debugging. In rare worst case I already reported bugs and regressions upstream to the AMD developers.

**Comment by MarioMey** [comment]
Sorry for not trying the new kernel. For the moment, I stay in my kernel and drivers. They work for my needs.

Thanks for your time.
