### ISSUE TITLE
Sorry to ask this here!

### ISSUE THREAD

**Issue by MarioMey** [M-Bab/linux-kernel-amdgpu-binaries#88]
I just bought a TP-Link WiFi adapter TL-WN8200ND and I was for 8 hours trying to make it work at full speed (it was slow and made all the system slow: BUG). Some minutes ago, I realized that that driver works correctly in kernels < 5.4!

Now, I booted in 4.19-09. But I amdgpu firmware doesn't work here!

Should I choose between using video hardware acceleration and my two monitors... or WiFi!

Didn't you compile kernels <5.4 with amd firmware?

**Comment by SebaUbuntu** [comment]
Latest 5.3 kernel: https://github.com/M-Bab/linux-kernel-amdgpu-binaries/tree/696088d6a8ad48e4f4506d1b9c66e63ccad93312
Latest 5.4 kernel: https://github.com/M-Bab/linux-kernel-amdgpu-binaries/tree/534cb88522e3579f6e4ef9064cb91c164e48d11c

**Comment by M-Bab** [comment]
Thanks @SebaUbuntu

**Comment by MarioMey** [comment]
@SebaUbuntu Thanks for that links. When I wrote <5.4 was because Debian showed me kernels 4.8, 4.9, 5.4, 5.5, and so, to install. The problem is that WiFi adapter drivers can be compiled in 4.9, but not in 5.4. I think the problems is kernel 5.x. For the moment, I'm on 4.9 and I could install amd drivers in this version using this [link](https://wiki.debian.org/AMDGPUDriverOnStretchAndBuster2).

Also, I could compile some WiFi driver in 5.6... but yesterday, computer hangs a little... so, I get back to 4.9. For now, I will be here.

Thanks!
