### ISSUE TITLE
evbug errors filling up system logs (possibly fixed already?)

### ISSUE THREAD

**Issue by mz1193** [M-Bab/linux-kernel-amdgpu-binaries#89]
I neglected to raise this issue when I first noticed it, but a couple of releases ago I noticed that this kernel spits out evbug errors like nobody's business, resulting in log files that take up GBs of space if ignored. It's easily solved by blacklisting evbug manually in /etc/modprobe.d, but I figured it was worth mentioning here just in case it hasn't been remedied.

For reference, my system is an Acer Nitro 5 laptop with an AMD Ryzen 7 2500u CPU and a Radeon RX 560x DGPU.

**Comment by M-Bab** [comment]
Do you have an example log line of that?

**Comment by M-Bab** [comment]
Closed because most probably fixed in the mean time.
