### ISSUE TITLE
Is there a way to reset the graphics drivers ?

### ISSUE THREAD

**Issue by stuaxo** [M-Bab/linux-kernel-amdgpu-binaries#90]
I guess many people like me don't have 100% stability on graphics, does anyone here know an incantation to reset the graphics drivers, (e.g. reload some modules) - I'm thinking that if it's possible, then I can at least hook that up to a keyboard shortcut.

My most recent crash on `5.6.19-20.07.09.amdgpu.ubuntu` happened when I ran katamari damarcy reroll, and caused sdma0 timeout after the intro:

```
Sep 03 19:42:18 computer kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring sdma0 timeout, signaled seq=185689, emitted seq=185689
Sep 03 19:42:18 computer kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* Process information: process  pid 0 thread  pid 0
```

Has anyone put together any scripts to grab the info from the last graphics crash ?
At the moment I `journalctl --boot=-1` then scroll up to find amdgpu.

**Comment by M-Bab** [comment]
You can try out the new kernel. I never needed to reset the graphic drivers. Instead I use the classic X-server restart if something breaks.

**Comment by JoneKone** [comment]
https://github.com/M-Bab/linux-kernel-amdgpu-binaries/issues/93 Related to my feature request that I closed :)

**Comment by stuaxo** [comment]
Closing it sounds like vendor_reset can do some of the versions, but not e.g. VEGA 8.
