### ISSUE TITLE
Dvi audio workaround

### ISSUE THREAD

**Issue by 1chard** [M-Bab/linux-kernel-amdgpu-binaries#91]
This kernel works like a charm talking about HDMI audio, and amdgpu video is working without black screen of death etc. 
But the dvi/hdmi cable doesn't work for the amd driver, and looks like there is no official support for audio over dvi monitor and/or coverters.

Is there any workaround for this? `aplay -l` return 6 audio outputs, there is 3 displayports 1 hdmi and 1 dvi at video card (Radeon RX 570)

**Comment by M-Bab** [comment]
I dont think this could ever work. DVI is like VGA an interface from the last century and was never designed to transport audio. Wikipedia mentions also AMD for a very special handling to somehow transport audio - maybe thats the reason it appears in linux. Nevertheless the chance that a monitor supports that is about 0%.

Putting adapters in between further decreases the chance to get anything working there. Go for HDMI-HDMI and DP-DP connections if you can. Maybe you can desribe the usecase more detailed so I can give a hint?
