### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by JoneKone** [M-Bab/linux-kernel-amdgpu-binaries#93]
Hi, i'm totally noob =D and don't know how stuff works.

This was originaly a level1forum project for vfio stuff but i think actually i'm sure it will help even normal users. 

https://github.com/gnif/vendor-reset

Is it possible to add this patch to your kernel?

**Comment by M-Bab** [comment]
That looks interesting but I think it is not meant to be build within the kernel. It is a kernel module and can be build and installed as such. dkms can help to auto-build it whenever new kernels are installed.

Overall I can't build kernels at the moment anyway. The sources deviated too far. I have to wait for AMD to rebase their code onto the 5.10 kernel.

**Comment by stuaxo** [comment]
I really hope they sort it out.   When they were failing they shrunk their Linux dev team, I hope now their doing well they grow it again if they haven't already.

**Comment by stuaxo** [comment]
It seems like vendor_reset is focused on AMD GPUs that can do VFIO - so it works with those, but not e.g. Vega GPUs.

@gnif [pointed out](https://github.com/gnif/vendor-reset/issues/8#issuecomment-750632992) that if anyone is interested in implementing this then the amdgpu source is the place to look, and indeed this looks interesting:

https://github.com/torvalds/linux/blob/master/drivers/gpu/drm/amd/amdgpu/amdgpu_device.c#L928
