### ISSUE TITLE
AMD Ryzen 5 3550H glitch

### ISSUE THREAD

**Issue by ArQ234** [M-Bab/linux-kernel-amdgpu-binaries#94]
Hello, and infinite thank's for your git, it's a real advantage to use your compilation method to unlock full power of the amd gpu drivers.
It's work on almost AMD GPU chipset but, some trouble is happening with some configuration, I think it's because kernel is a little out of date now. I try the last ubuntu with out modification and, clearly this amd gpu was a disaster on it : system crash when you use video player. Personnaly I use debian and with your method, it's almost perfect but :
Ryzen 7 3700U can't wake up from sleep
Ryzen 5 3550H have serious visual glitch

If you have time in the future, can you update your git with new linux kernel and update AMD files ?
I'm really too noob on linux to do it myself, (less one year on linux) but I'm ready to help if I can.
thank a lot/

**Comment by M-Bab** [comment]
Please let me know if the 5.11 actually helped on any of your issues. But it's always the same: Best thing I can do is continuously building these kernels and the best thing you can do is try them out.

In extreme cases of clear bugs that remain for a long time, I also have reported bugs upstream to the AMD linux developers. But thats rare.

**Comment by M-Bab** [comment]
@ArQ234 can you check again with the latest kernel? The previous 5.11 had some issues.
