### ISSUE TITLE
Page Fault on linux-5.11.8 using AMDGPU on GCN1.0 card

### ISSUE THREAD

**Issue by dukenukemx** [M-Bab/linux-kernel-amdgpu-binaries#95]
I installed your 5.11.8 Linux kernel in Linux Mint 20 and I'm using a Radeon HD 7850.  I have, "GRUB_CMDLINE_LINUX=" radeon.si_support=0 radeon.cik_support=0 amdgpu.si_support=1 amdgpu.cik_support=1" in grub.  When trying to boot I get a page fault.  

![IMG_20210330_142916 1](https://user-images.githubusercontent.com/31163475/113038997-2d242500-9165-11eb-9dbe-d8c92ca1de17.jpg)
![IMG_20210330_142924 1](https://user-images.githubusercontent.com/31163475/113039031-34e3c980-9165-11eb-9369-3972694a1f95.jpg)

**Comment by M-Bab** [comment]
I am not entirely happy with this kernel either. I got some graphical artifacts in a 3d game. I guess on the next chance (maybe weekend) I will start over and build/merge it from amd-staging-drm-next another time.

**Comment by dukenukemx** [comment]
I haven't been able to use AMDGPU on my GCN1.0 Radeon HD 7850 on kernels newer than 5.8.  That's why I tried this kernel out to see if it supports AMDGPU on GCN1.0 cards.  Anything 5.9 and newer won't work.  The issue I'm having with this kernel maybe related to it.

**Comment by Mr-Precise** [comment]
The problem really exists
Does not work on Radeon HD 7750 on kernel 5.11.6 and 5.11.8.

**Comment by M-Bab** [comment]
You can try again. At least for me the new kernel works fine.

**Comment by M-Bab** [comment]
You can try again with the new 5.13 kernel.

**Comment by dukenukemx** [comment]
Thanks, I'll give it a try later.

**Comment by M-Bab** [comment]
So I am closing this for now. Reopen if the problem persists with 5.13.
