### ISSUE TITLE
AMD RX6700XT on Debian Sid

### ISSUE THREAD

**Issue by riot-user** [M-Bab/linux-kernel-amdgpu-binaries#97]
Hello,
I installed the new RX6700XT and it is not recognized on Debian Sid (llvmpipe).
Nothing changed with the new kernel, no driver.
The enclosed AMD 2400G is working without problems.
inxi -G:
  Device-1: AMD Navi 22 [Radeon RX 6700/6700 XT / 6800M] driver: N/A 
  Device-2: AMD Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] 
  driver: N/A 
  Display: x11 server: X.Org 1.20.11 driver: loaded: ati,vesa 
  unloaded: fbdev,modesetting,radeon resolution: 1920x1080~77Hz 
  OpenGL: renderer: llvmpipe (LLVM 11.0.1 256 bits) v: 4.5 Mesa 20.3.5

**Comment by M-Bab** [comment]
That's weird. This should already work with the regular 4.11 kernel. And your mesa version is also pretty new. Compare here: https://www.phoronix.com/scan.php?page=article&item=radeon-rx6700xt-linux&num=1

> When it comes to upstream open-source driver support for the Radeon RX 6700 XT, it remains the usual case of: the newer, the better. The Radeon RX 6700 XT review sample I received from AMD was working fine on Linux 5.11+ and was using Mesa 21.1-devel though Mesa 20.0 and potentially 19.3 should work too. However, in the case of new GPUs especially and with the RadeonSI and RADV Mesa drivers continuing to rapidly advance, with a new GPU family you really want to be using the latest stable or development builds for the best features and performance. The benchmarks in this article were running on Mesa 21.1-devel with Linux 5.12 Git, but Linux 5.11 stable was thoroughly tested too with good success.

So this kernel should definitely work as well. What is the output of `sudo dmesg | grep drm` ?

**Comment by riot-user** [comment]
Thank you for the quick response.
dmesg | grep drm
has no output.

**Comment by riot-user** [comment]
I reinstalled Debian Sid connected to the external RX6700XT and now it works, but it shows many graphic errors.

**Comment by M-Bab** [comment]
You can try again with the new 5.13 kernel.

**Comment by riot-user** [comment]
Thank you very much M-Bab!!
5.13 worked much better :-).
But now the regular 5.14 kernel worked also.
