### ISSUE TITLE
AMD Radeon pro Vega 20 (aka vega12)

### ISSUE THREAD

**Issue by RodrigoLuglio** [M-Bab/linux-kernel-amdgpu-binaries#98]
I have a macbook pro with vega 20 which uses the amdgpu firmware vega12 and when i boot any distro the graphics glitch and the computer freezes. If i install amdgpu pro on ubuntu it works flawlessly. Would you guys help me debug this and fix for upstream? 
Please, excuse me if this is not the right place for me to ask this kind of thing, and please if you can, kindly redirect me to the right place.

**Comment by M-Bab** [comment]
You can try again with the new 5.13 kernel.

**Comment by RodrigoLuglio** [comment]
I will do and let you know! Thank you a lot for the follow up

**Comment by M-Bab** [comment]
So I am closing this for now.
