### ISSUE TITLE
Le9 patches

### ISSUE THREAD

**Issue by stuaxo** [M-Bab/linux-kernel-amdgpu-binaries#99]
Hi,
   Would you consider including the Le9 patches ?   https://www.phoronix.com/scan.php?page=news_item&px=le9-Linux-Low-RAM

"Livelocking" the system is something I've managed to do from time to time with Linux for over a decade, probably because, I sometimes push the system too far as a developer.

Cheers
Stuart

**Comment by M-Bab** [comment]
This is not really the focus of this kernel here. But if you like the sources are available here: https://github.com/M-Bab/linux-kernel-amdgpu . You can try to patch it in and build the patched kernel yourself.
